#if !defined(AFX_AVVIEWX_H__C0085603_AC9A_11D3_8B77_00A0246BC0BD__INCLUDED_)
#define AFX_AVVIEWX_H__C0085603_AC9A_11D3_8B77_00A0246BC0BD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVViewX wrapper class

class CVViewX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CVViewX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8718c658, 0x8956, 0x11d2, { 0xbd, 0x21, 0x0, 0x60, 0xb0, 0xa1, 0x2a, 0x50 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetBorderStyle(long nNewValue);
	long GetBorderStyle();
	void SetEnabled(BOOL bNewValue);
	BOOL GetEnabled();
	long GetWindow();
	void SetAppearance(short nNewValue);
	short GetAppearance();
	CString GetUserMode();
	void SetUserMode(LPCTSTR lpszNewValue);
	BOOL GetHighlightLinks();
	void SetHighlightLinks(BOOL bNewValue);
	CString GetSrc();
	void SetSrc(LPCTSTR lpszNewValue);
	CString GetLayersOn();
	void SetLayersOn(LPCTSTR lpszNewValue);
	CString GetLayersOff();
	void SetLayersOff(LPCTSTR lpszNewValue);
	CString GetSrcTemp();
	void SetSrcTemp(LPCTSTR lpszNewValue);
	CString GetSupportPath();
	void SetSupportPath(LPCTSTR lpszNewValue);
	CString GetFontPath();
	void SetFontPath(LPCTSTR lpszNewValue);
	CString GetNamedView();
	void SetNamedView(LPCTSTR lpszNewValue);
	CString GetGeometryColor();
	void SetGeometryColor(LPCTSTR lpszNewValue);
	CString GetPrintBackgroundColor();
	void SetPrintBackgroundColor(LPCTSTR lpszNewValue);
	CString GetPrintGeometryColor();
	void SetPrintGeometryColor(LPCTSTR lpszNewValue);
	CString GetShadingMode();
	void SetShadingMode(LPCTSTR lpszNewValue);
	CString GetProjectionMode();
	void SetProjectionMode(LPCTSTR lpszNewValue);
	CString GetEnableUIMode();
	void SetEnableUIMode(LPCTSTR lpszNewValue);
	CString GetLayout();
	void SetLayout(LPCTSTR lpszNewValue);
	void SetBackgroundColor(LPCTSTR lpszNewValue);
	CString GetBackgroundColor();
	void Update();
	void ShowLayersDialog();
	void ShowNamedViewsDialog();
	void ShowLayoutsDialog();
	void ShowPrintDialog();
	void SetOleObjectHandler(LPUNKNOWN punk);
	void GetDrawingExtents(double* left, double* right, double* bottom, double* top);
	void GetCurrentView(double* left, double* right, double* bottom, double* top);
	void SetCurrentView(double left, double right, double bottom, double top);
	void ShowAboutDialog();
	void InvokeURL(LPCTSTR url);
	void ShowSaveAsDialog();
	void ShowOptionsDialog();
	void ShowSaveMarkupDialog();
	void SaveMarkup(LPCTSTR filename);
	BOOL ClearMarkup();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AVVIEWX_H__C0085603_AC9A_11D3_8B77_00A0246BC0BD__INCLUDED_)
