#
# ID's of resources
ABOUT_ID=512
ABOUT_VERSION_ITEM=2

MEMORY_ALERT_ID=514

ID_SELECT_DIALOG=616
ID_TRACE_DIALOG=621
ITEM_SELECT_OK=1
ITEM_SELECT_CANCEL=2
ITEM_SELECT_LISTPROMPT=3
ITEM_SELECT_ITEMLIST=4
ITEM_SELECT_BALLOONHELP=5

# Input dialogs
ID_INPUT_DIALOG=524
ID_INPUTURL_DIALOG=525
ID_PASSWD_DIALOG=526
ID_NEWCHANNEL_DIALOG=627
ITEM_INPUT_OK=1
ITEM_INPUT_CANCEL=2
ITEM_INPUT_TEXT=3
ITEM_INPUTURL_BROWSE=4
ITEM_NEWCHANNEL_TYPE=5
ITEM_NEWCHANNEL_BALLOONHELP=6

# For messages and questions:
ID_MESSAGE_DIALOG=521
ID_QUESTION_DIALOG=522
ITEM_QUESTION_OK=1
ITEM_QUESTION_TEXT=2
ITEM_QUESTION_CANCEL=3

#  Common resources
ID_DIALOG_PREFERENCES=528

# Editor-only resources
ID_DIALOG_LINKBROWSE=617
ID_DIALOG_ANCHOR=618
ID_DIALOG_ARCINFO=619
ID_DIALOG_LAYOUT=626
ID_DIALOG_UGROUP_BROWSER=628
ID_DIALOG_UGROUP_EDITOR=629
ID_DIALOG_LINKEDIT=630

# Property sheets
ID_DIALOG_ATTREDIT=623
ID_DIALOG_ATTREDIT_STRING=635
ID_DIALOG_ATTREDIT_FILE=636
ID_DIALOG_ATTREDIT_COLOR=637
ID_DIALOG_ATTREDIT_OPTION=638
ID_DIALOG_ATTREDIT_CHANNEL=639
ID_DIALOG_ATTREDIT_INFO=640
ID_DIALOG_ATTREDIT_GENERAL=641
ID_DIALOG_ATTREDIT_TIMING=642
ID_DIALOG_ATTREDIT_TARGET_AUDIENCE=643
ID_DIALOG_ATTREDIT_TEXT=644
ID_DIALOG_ATTREDIT_CLIP=645
ID_DIALOG_ATTREDIT_SYSTEM_PROPERTIES=646
ID_DIALOG_ATTREDIT_CONVERSION=647
ID_DIALOG_ATTREDIT_UPLOAD=648
ID_DIALOG_ATTREDIT_WIPE=649
ID_DIALOG_ATTREDIT_TRANSITION=650
ID_DIALOG_ATTREDIT_IMAGE_CONVERSION=651
ID_DIALOG_ATTREDIT_DESTINATION_AREA=652
ID_DIALOG_ATTREDIT_SOURCE_AREA=653
ID_DIALOG_ATTREDIT_CH_AREA=654
ID_DIALOG_ATTREDIT_CH_GENERAL=655

ID_TEMPLATE_DIALOG=633
ITEM_TEMPLATE_OK=1
ITEM_TEMPLATE_CANCEL=2
ITEM_TEMPLATE_POPUP=3
ITEM_TEMPLATE_DESCRIPTION=4
ITEM_TEMPLATE_IMAGE=5

ID_DIALOG_BANDWIDTH=634
ITEM_BANDWIDTH_OK=1
ITEM_BANDWIDTH_CANCEL=2
ITEM_BANDWIDTH_HELP=3
# group is 4
ITEM_BANDWIDTH_MESSAGE=5
ITEM_BANDWIDTH_ERRORS=7
ITEM_BANDWIDTH_STALLTIME=9
ITEM_BANDWIDTH_STALLCOUNT=11
ITEM_BANDWIDTH_PREROLL=13
ITEM_BANDWIDTH_MESSAGE2=14

# Icon IDs
ID_ICON_TRIANGLE_RIGHT=612		# Mac-style right-pointing reveal triangle
ID_ICON_TRIANGLE_DOWN=613		# Mac-style down-pointing reveal triangle
ID_ICON_BANDWIDTH_OK=614		# green pipeline
ID_ICON_BANDWIDTH_ERROR=615		# red bulging pipeline
##ID_ICON_TRIANGLE_RIGHT=616	# Windows-style boxed +
##ID_ICON_TRIANGLE_DOWN=617		# Windows-style boxed -
ID_ICON_ERROR=618				# Warning trafficsign
ID_ICON_LINKSRC=621				# Source of hyperlinks
ID_ICON_LINKDST=620				# Destination of hyperlinks
##ID_ICON_LINKSRCDST=619		# Both source and destination
ID_ICON_LINKSRCDST=622			# Both source and destination
