#
# ID's of resources
ABOUT_ID=512
ABOUT_VERSION_ITEM=2

ID_SELECT_DIALOG=616
ITEM_SELECT_OK=1
ITEM_SELECT_CANCEL=2
ITEM_SELECT_LISTPROMPT=3
ITEM_SELECT_ITEMLIST=4
ITEM_SELECT_SELECTPROMPT=5
ITEM_SELECT_ITEM=6
ITEM_SELECT_BALLOONHELP=7

# Input dialogs
ID_INPUT_DIALOG=524
ID_INPUTURL_DIALOG=525
ID_NEWCHANNEL_DIALOG=627
ITEM_INPUT_OK=1
ITEM_INPUT_CANCEL=2
ITEM_INPUT_TEXT=3
ITEM_INPUTURL_BROWSE=4
ITEM_NEWCHANNEL_TYPE=5
ITEM_NEWCHANNEL_BALLOONHELP=6

# For messages and questions:
ID_MESSAGE_DIALOG=521
ID_QUESTION_DIALOG=522
ITEM_QUESTION_OK=1
ITEM_QUESTION_TEXT=2
ITEM_QUESTION_CANCEL=3

#  Common resources
ID_DIALOG_PREFERENCES=528

# Editor-only resources
ID_DIALOG_LINKEDIT=617
ID_DIALOG_ANCHOR=618
ID_DIALOG_ARCINFO=619
ID_DIALOG_NODEINFO=620
ID_DIALOG_NODEATTR=623
ID_DIALOG_LAYOUT=626
ID_DIALOG_UGROUP_BROWSER=628
ID_DIALOG_UGROUP_EDITOR=629
