//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GRiNSRes.rc
//
#define IDC_REPLACEALL                  3
#define IDS_ABOUTBOX                    101
#define IDD_GRINSEDBAR                  194
#define IDC_POINT_HAND                  195
#define IDD_CREATE_BOX                  196
#define IDD_SPLASH                      197
#define IDI_GRINS_ED                    198
#define IDD_DIALOG_OPENLOCATION         199
#define IDR_GRINSED                     200
#define IDR_TB_EDITOR                   200
#define IDD_LAYOUT                      201
#define IDD_NEW_CHANNEL                 202
#define IDD_LAYOUT_NAME                 203
#define IDD_FORM                        204
#define IDD_EDITSTRINGATTR              206
#define IDD_EDITOPTIONSATTR             207
#define IDD_EDITFILEATTR                208
#define IDD_STDDLGBAR                   209
#define IDD_NODE_INFO_CMDBAR            212
#define IDD_LINKS                       214
#define IDD_SELECT_ONE                  218
#define IDD_MESSAGE_BOX                 221
#define IDB_SPLASH                      222
#define IDD_PREFERENCES                 223
#define IDD_ABOUT                       225
#define IDB_SPLASHLITE                  226
#define IDD_EDIT_USERGROUP              227
#define IDD_USERGROUP                   228
#define IDR_GRINS                       229
#define IDD_LINK_PROPERTY               230
#define IDI_CREATE_BOX                  231
#define IDD_EDIT_ANCHORS                232
#define IDD_ARC_INFO_FORM               233
#define IDD_NODE_INFO                   234
#define IDD_EDITCOLORATTR               235
#define IDC_DRAGMOVE                    237
#define IDC_DRAGLINK                    238
#define IDB_SPLASHPLAY                  243
#define IDD_LICENSE                     244
#define IDD_CHANNEL_UNDEF               245
#define IDI_GRINS_QUESTION              246
#define IDI_GRINS_INFO                  247
#define IDI_GRINS_STOP                  248
#define IDD_ENTER_KEY                   249
#define IDD_INTERNAL                    250
#define IDR_STRUCT_EDIT                 251
#define IDD_FORM1                       252
#define IDD_EDITATTR_SHEET              253
#define IDD_EDITCOLORATTR1              254
#define IDD_EDITATTR_C1                 255
#define IDD_EDITCOLORATTR2              256
#define IDD_DIALOG1                     257
#define IDD_EDITFILEATTR1               258
#define IDD_EDITATTR_F1                 259
#define IDD_EDITOPTIONSATTR1            260
#define IDD_EDITATTR_O1                 261
#define IDD_EDITSTRINGATTR1             262
#define IDD_EDITATTR_S1                 263
#define IDD_EDITRECTATTR                264
#define IDD_EDITRECTATTR1               265
#define IDD_EDITATTR_LS1                266
#define IDD_EDITATTR_2LIST              267
#define IDD_PASSWD_DIALOG               268
#define IDD_TEMPLATE_DIALOG             269
#define IDD_PROGRESS                    270
#define IDD_INIT_DIALOG                 271
#define IDD_EDITATTR_R6                 272
#define IDD_EDITATTR_C6                 273
#define IDI_ICON_OPEN                   274
#define IDI_ICON_CLOSED                 275
#define IDI_ICON_BANDWIDTHBAD           276
#define IDI_ICON_BANDWIDTHGOOD          277
#define IDI_ICON_ERROR                  278
#define IDD_BANDWIDTH_DIALOG            279
#define IDI_PLAY                        280
#define IDI_STOP                        281
#define IDI_PAUSE                       282
#define IDR_ATTR_EDIT                   283
#define IDI_ICON_LINKSRC                284
#define IDI_ICON_LINKDST                285
#define IDI_ICON_LINKSRCDST             286
#define IDC_DRAG_HAND                   287
#define IDB_SPLASHPRO                   288
#define IDB_SPLASHSMIL                  289
#define IDB_SPLASHQTPRO                 290
#define IDB_SPLASHSMIL2                 291
#define IDB_BITMAP1                     292
#define IDB_SPLASHSNAP                  293
#define IDB_BITMAP2                     294
#define IDI_ICON_TRANSOUT               295
#define IDI_ICON_TRANSIN                296
#define IDB_VIEWPORT                    297
#define IDB_REGION                      298
#define IDB_IMAGE                       299
#define IDB_VIDEO                       300
#define IDB_TEXT                        301
#define IDB_HTML                        302
#define IDB_SOUND                       303
#define IDI_EVENTIN                     304
#define IDI_EVENTINXX                   304
#define IDI_EVENTOUT                    305
#define IDI_CAUSEEVENT                  306
#define IDI_HAPPYFACE                   307
#define IDI_SPACEMAN                    308
#define IDI_WALLCLOCK                   309
#define IDI_REPEAT                      310
#define IDI_FOCUSIN                     311
#define IDI_ACTIVATEEVENT               312
#define IDI_DURATION                    313
#define IDI_ANIMATION                   314
#define IDR_TB_PLAYER                   315
#define IDR_TB_COMMON                   315
#define IDI_PLAYING                     316
#define IDI_WAITSTOP                    317
#define IDD_SOURCEEDIT                  318
#define IDI_IDLE                        319
#define IDR_TB_ALIGNMENT                320
#define IDR_TB_UNUSED                   320
#define IDD_EDITATTR_LIST               321
#define IDB_SPLASHSMILBOSTON            321
#define IDD_EVENT                       322
#define IDD_EDITSTRINGATTR2             323
#define IDD_EDITATTR_S7                 324
#define IDD_EDITATTR_S5                 325
#define IDD_EDITATTR_S2                 326
#define IDD_EDITATTR_LS2                327
#define IDD_EDITATTR_LS1O1              328
#define IDD_EDITATTR_S1O1S5             329
#define IDD_EDITATTR_S1O1               330
#define IDD_EDITATTR_O1_R2              331
#define IDD_EDITATTR_R2                 332
#define IDD_EDITATTR_O1_R3              333
#define IDD_EDITATTR_R3                 334
#define IDD_EDITATTR_S1O1S5_R3          335
#define IDD_EDITATTR_S1R3S5             336
#define IDD_EDITATTR_O1_R4              337
#define IDD_EDITATTR_R4                 338
#define IDD_EDITATTR_LS1O2              339
#define IDD_EDITATTR_LS102              340
#define IDD_EDITATTR_S6                 341
#define IDD_EDITATTR_S4                 342
#define IDD_EDITATTR_S3                 343
#define IDD_EDITATTR_PF1                344
#define IDD_EDITATTR_E1                 345
#define IDD_EDITATTR_S1O1C              346
#define IDD_EDITATTR_FO1                347
#define IDD_EDITATTR_PREV_TEMP          348
#define IDD_EDITATTR_S1R3S4             349
#define IDD_EDITATTR_S1O2               350
#define IDD_EDITATTR_P4                 351
#define IDD_EDITATTR_R24                352
#define IDD_EDITATTR_MF1                353
#define IDD_EDITATTR_CH1                354
#define IDD_EDITATTR_D1                 355
#define IDD_EDITATTR_LS1O3              356
#define IDD_EDITATTR_TF1                357
#define IDD_EDITATTR_T3                 358
#define IDD_EDITATTR_T2                 359
#define IDD_EDITATTR_LS1O3a             360
#define IDD_EDITATTR_LS1O2a             361
#define IDD_EDITATTR_LS1O3b             362
#define IDD_EDITATTR_T4                 363
#define IDD_EDITATTR_T3C                364
#define IDD_EDITATTR_DR3                365
#define IDD_EDITATTR_ANCHOR1            366
#define IDD_ANCHOR_NAME                 367
#define IDD_EDITATTR_CK1                368
#define IDD_EDITATTR_CONV3              369
#define IDD_EDITATTR_CONV2              370
#define IDD_EDITATTR_CONV4              371
#define IDD_EDITATTR_CONV5              372
#define IDD_EDITATTR_S2a                373
#define IDD_EDITATTR_CONV1              374
#define IDD_EDITATTR_QTMEDIAPREF        375
#define IDD_EDITATTR_S3R2               376
#define IDD_EDITATTR_O1S2               378
#define IDD_PREFERENCES2                379
#define IDD_LAYOUT2                     380
#define IDD_EDITATTR_LS1O4              381
#define IDD_EDITATTR_GENERAL            382
#define IDD_EDITATTR_O2                 383
#define IDD_EDITATTR_TRANSITION         384
#define IDD_EDITATTR_SUBREGION          385
#define IDD_LAYOUT3                     386
#define IDD_EDITATTR_COLORSEL           387
#define IDD_SEEK                        388
#define IDD_LAYOUT_T1                   389
#define IDD_EDITATTR_LS1x               390
#define IDD_SOURCEEDIT1                 391
#define IDD_EDITATTR_QTPREF             392
#define IDD_LAYOUT_T2                   393
#define IDI_ZOOMOUT                     394
#define IDD_EDITATTR_EMPTY              395
#define IDI_ZOOMIN                      396
#define IDI_ICON_PAROPEN                397
#define IDI_ICON_EXCLOPEN               398
#define IDI_ICON_SWITCHOPEN             399
#define IDI_ICON_PRIOOPEN               400
#define IDI_ICON_SEQOPEN                401
#define IDI_ICON_PARCLOSED              402
#define IDI_ICON_SEQCLOSED              403
#define IDI_ICON_SWITCHCLOSED           404
#define IDI_ICON_PRIOCLOSED             405
#define IDI_ICON_EXCLCLOSED             406
#define IDD_EDITATTR_EVENTLIST          407
#define IDI_ICON_ASSET_AUDIO            408
#define IDD_ASSETSBAR                   409
#define IDI_ICON_ASSET_VIDEO            410
#define IDD_WALLCLOCKPOPUP              411
#define IDI_ICON_ASSET_BLANK            412
#define IDD_EDITATTR_ACTIVEDUR1         413
#define IDI_ICON_ASSET_IMAGE            414
#define IDD_EDITATTR_LAYOUT1            415
#define IDI_ICON_ASSET_TEXT             416
#define IDD_EDITATTR_LAYOUT2            417
#define IDB_SVG                         418
#define IDD_EDITATTR_S1R3S6             419
#define IDD_EDITATTR_SYNCHRONIZATION    420
#define IDI_ICON_NODE                   421
#define IDD_EDITATTR_ACTIVEDUR2         422
#define IDD_EDITATTR_MF2                423
#define IDD_EDITATTR_PF2                424
#define IDD_EDITATTR_F2                 425
#define IDD_EDITATTR_EVENTLIST2         426
#define IDD_EDITATTR_LAYOUT3            427
#define IDD_EDITATTR_INFO1              428
#define IDD_EDITATTR_ID1                429
#define IDD_EDITATTR_ID2                430
#define IDD_EDITATTR_ID3                431
#define IDD_EDITATTR_REGIONNAME         432
#define IDD_EDITATTR_VIEWPORTNAME       433
#define IDD_SELECT_MULTI                434
#define IDI_DANGLINGEVENT               435
#define IDD_FIND                        436
#define IDI_DANGLINGANCHOR              437
#define IDD_REPLACE                     438
#define IDI_PROPERTIES                  439
#define IDD_EDITATTR_BRUSH              440
#define IDI_VIEWPORT                    441
#define IDD_EDITATTR_S1R3S7             442
#define IDI_REGION                      443
#define IDD_EDITATTR_CH2                444
#define IDR_SOURCE_EDIT                 445
#define IDI_BRUSH                       446
#define IDI_ANIMATE                     447
#define IDD_SELECT_ELEMENT              448
#define IDD_EDITATTR_ANIMATETARGET      449
#define IDD_EDITATTR_ITRANSITION        450
#define IDD_EDITATTR_ANIMATEGENERAL     451
#define IDD_EDITATTR_ANIMATEGENERALM    452
#define IDI_UNKNOWN                     453
#define IDD_TEST1                       454
#define IDD_TEST2                       455
#define IDD_ANIMATE                     456
#define IDI_OPENEDEYE                   459
#define IDI_OPENEDEYEKEY                460
#define IDI_CLOSEDEYE                   462
#define IDD_REGISTER                    463
#define IDI_PAUSING                     463
#define IDD_EDITATTR_GEOMETRY           464
#define IDB_SPLASHREALONE               464
#define IDI_ICON_BROWSER                464
#define IDD_EDITATTR_LAYOUT2REAL        465
#define IDI_ICON_CONTEXT                465
#define IDC_DARROW                      465
#define IDD_EDITATTR_REALEXTENSION      466
#define IDI_ICON_MEDIACLOSED            466
#define IDC_DARROWHIT                   466
#define IDD_EDITATTR_S7F                467
#define IDI_ICON_MEDIAOPEN              467
#define IDD_EDITATTR_SERVER             468
#define IDD_EDITATTR_S1R3S8             469
#define IDD_EDITATTR_REALEXTENSION2     470
#define IDD_EDITATTR_ACTIVEDUR3         471
#define IDD_EDITATTR_ACTIVEDUR4         472
#define IDD_EDITATTR_PRIO               473
#define IDD_EDITATTR_S4F                474
#define IDD_EDITATTR_SYNC               475
#define IDD_EDITATTR_ANIMATETARGETMOTION 476
#define IDD_EDITATTR_ANIMATETARGETSET   477
#define IDD_EDITATTR_ANIMATEVALUES      478
#define IDD_EDITATTR_ACTIVEDUR          479
#define IDD_EDITATTR_ANCHOR             480
#define IDD_EDITATTR_ANCHOR2            480
#define IDD_EDITATTR_LINK               481
#define IDD_EDITATTR_EMPTYGROUP         481
#define IDD_EDITATTR_NONEMPTYGROUP      482
#define IDD_EDITATTR_TEMPLATE1          483
#define IDD_EDITATTR_TEMPLATE0          484
#define IDD_EDITATTR_TEMPLATE2          485
#define IDD_EDITATTR_PREFPRO            486
#define IDC_CDARROW                     487
#define IDD_EDITATTR_DOCTEMPLATE        487
#define IDC_CDARROWHIT                  488
#define IDC_SPLASH                      1001
#define IDC_EXPLANATION                 1002
#define IDC_LAYOUT_CHANNELS             1003
#define IDC_EDIT2                       1004
#define IDC_COMBO1                      1005
#define IDC_CKTV2                       1005
#define IDC_82                          1006
#define IDC_CKTV3                       1006
#define IDC_LAYOUT_BRINGFRONT           1007
#define IDC_OTHER_CHANNELS              1008
#define IDUC_RESET2                     1009
#define IDC_STATIC1                     1010
#define IDUC_RESET4                     1011
#define IDUC_EDIT                       1012
#define IDUC_RESET6                     1013
#define IDUC_RESET7                     1014
#define IDC_EDIT5                       1015
#define IDC_BITRV                       1015
#define IDC_LAYOUT_NEWREGION            1016
#define IDC_COMBO2                      1017
#define IDC_LIST2                       1018
#define IDC_BUTTON_BROWSE               1019
#define IDC_EDIT_LOCATION               1020
#define IDC_TAB_GRINSVIEWS              1021
#define IDCMD_NEW_LAYOUT                1022
#define IDCMD_RENAME                    1023
#define IDCMD_DELETE                    1024
#define IDC_LAYOUTS                     1025
#define IDC_CHANNEL_NAME                1026
#define IDC_CHANNEL_TYPE                1027
#define IDC_EDIT1                       1028
#define IDC_WIDTHV                      1029
#define IDCMD_NEW_CHANNEL               1030
#define IDC_RIGHTV                      1030
#define IDCMD_REMOVE_CHANNEL            1031
#define IDC_TOPV                        1031
#define IDCMD_ATTRIBUTES                1032
#define IDC_HEIGHTV                     1032
#define IDC_LAYOUT_BACKGROUND           1033
#define IDC_BOTTOMV                     1033
#define IDCMD_ADD_CHANNEL               1034
#define IDC_ZV                          1034
#define IDC_LAYOUT_SENDBACK             1035
#define IDC_SOUNDLEVELV                 1035
#define IDUC_APPLY                      1036
#define IDC_LAYOUT_DELREGION            1037
#define IDC_LAYOUT_HIDEMEDIA            1038
#define IDC_LAYOUT_NEWVIEW              1039
#define IDC_LAYOUT_HIDEREGION           1040
#define IDUC_RESET                      1043
#define IDUC_BROWSE                     1044
#define IDUC_RESET3                     1045
#define IDUC_NEW                        1046
#define IDUC_RESET5                     1047
#define IDUC_DELETE                     1048
#define IDUC_EXPORT                     1049
#define IDUC_NODE_ATTRIBUTES            1051
#define IDUC_CHANNEL_ATTRIBUTES         1052
#define IDUC_ANCHORS                    1053
#define IDUC_CANCEL                     1054
#define IDUC_OK                         1055
#define IDC_PUSH_FOCUS1                 1056
#define IDC_ANCHOR_EDITOR1              1057
#define IDC_PUSH_FOCUS2                 1058
#define IDC_ANCHOR_EDITOR2              1059
#define IDC_ADD_LINK                    1060
#define IDC_EDIT_LINK                   1061
#define IDC_DELETE_LINK                 1062
#define IDC_RADIO1                      1063
#define IDC_RADIO2                      1064
#define IDC_RADIO3                      1065
#define IDC_RADIO4                      1067
#define IDC_RADIO5                      1068
#define IDC_RADIO6                      1069
#define IDC_EDIT7                       1070
#define IDC_EDIT9                       1071
#define IDC_SC                          1071
#define IDC_LIST1                       1072
#define IDC_LIST3                       1073
#define IDC_LEFT_MENU                   1074
#define IDC_RIGHT_MENU                  1075
#define IDC_STATIC_LEFT                 1076
#define IDC_STATIC_RIGHT                1077
#define IDC_OPENCHILD                   1078
#define IDC_LIST_LINKS                  1080
#define IDC_RESET                       1081
#define IDC_CHECK1                      1082
#define IDC_CHECK2                      1083
#define IDC_NODE_TYPE                   1085
#define IDC_NODE_NAME                   1088
#define IDC_CHANNEL                     1089
#define IDC_EXT_EDIT                    1090
#define IDC_IMM_EDIT                    1091
#define IDC_INT_LIST                    1092
#define IDC_MESSAGE                     1097
#define IDC_VERSION_MSG                 1098
#define IDC_LINK_D                      1099
#define IDC_LINK_T                      1100
#define IDCMD_NEW_GROUP                 1101
#define IDCMD_EDIT_GROUP                1102
#define IDC_GROUPS                      1103
#define IDC_APPLY                       1104
#define IDCMD_DELETE_GROUP              1105
#define IDC_CHECK3                      1107
#define IDC_CHECK4                      1108
#define IDUC_BUY                        1119
#define IDUC_EVALLICENSE                1120
#define IDUC_ENTERKEY                   1121
#define IDUC_OPENFILE                   1122
#define IDC_LEAVE_UNDEF                 1124
#define IDC_STATIC_ICON                 1127
#define IDC_KEY                         1129
#define IDC_NAME                        1130
#define IDC_ORGANIZATION                1131
#define IDC_NULL                        1132
#define IDC_ATTR_INFO                   1134
#define IDUC_RESET1                     1136
#define IDC_EDIT12                      1137
#define IDC_TZMN                        1137
#define IDC_EDIT3                       1138
#define IDC_EDIT4                       1139
#define IDC_DY                          1139
#define IDC_VALUESV                     1139
#define IDC_TABINDEXV                   1139
#define IDC_EDIT6                       1140
#define IDC_HR                          1140
#define IDC_EDIT8                       1141
#define IDC_MN                          1141
#define IDC_EDIT10                      1142
#define IDC_EDIT14                      1143
#define IDC_EDIT15                      1144
#define IDC_1                           1145
#define IDC_2                           1146
#define IDC_3                           1147
#define IDC_4                           1148
#define IDC_5                           1149
#define IDC_6                           1150
#define IDC_21                          1151
#define IDC_CLIPBEGINL                  1151
#define IDC_22                          1152
#define IDC_CLIPENDL                    1152
#define IDC_23                          1153
#define IDC_READINDEXL                  1153
#define IDC_11                          1154
#define IDC_EVENTSENSITIVITYL           1154
#define IDC_12                          1155
#define IDC_13                          1156
#define IDC_ERASEL                      1156
#define IDC_31                          1157
#define IDC_32                          1158
#define IDC_34                          1159
#define IDC_SAUDIODESCL                 1159
#define IDC_41                          1160
#define IDC_GROUP8                      1160
#define IDC_42                          1161
#define IDC_43                          1162
#define IDC_51                          1163
#define IDC_SHOWHIDDENL                 1163
#define IDC_52                          1164
#define IDC_53                          1165
#define IDC_SCOMPONENTL                 1165
#define IDC_61                          1166
#define IDC_62                          1167
#define IDC_63                          1168
#define IDC_SCOMPONENTV                 1168
#define IDC_71                          1169
#define IDC_72                          1170
#define IDC_73                          1171
#define IDC_SOPERATINGSYSTEML           1171
#define IDC_27                          1172
#define IDC_SOPERATINGSYSTEMV           1172
#define IDC_24                          1173
#define IDC_SCPUL                       1173
#define IDC_25                          1174
#define IDC_SCPUV                       1174
#define IDC_SAUDIODESCV1                1175
#define IDC_16                          1176
#define IDC_SCUSTOMTESTSL               1176
#define IDC_SHOWHIDDENV1                1176
#define IDC_14                          1177
#define IDC_SCUSTOMTESTSV               1177
#define IDC_15                          1178
#define IDC_SOPERATINGSYSTEML2          1178
#define IDC_DUBSUBL                     1178
#define IDC_17                          1179
#define IDC_SCALE1                      1180
#define IDC_TEMPLATECOMBO               1181
#define IDC_PICTURE                     1182
#define IDC_TARGET_EXTERN               1183
#define IDC_TARGET_EMBEDDED             1184
#define IDC_BUTTON1                     1186
#define IDC_PREVIEW                     1186
#define IDC_BUTTON4                     1187
#define IDC_INIT_NEW                    1188
#define IDC_INIT_OPEN                   1189
#define IDC_INIT_NOTHING                1190
#define IDC_INIT_RECENT                 1190
#define IDC_INIT_NEVER_AGAIN            1191
#define IDC_8                           1192
#define IDC_INIT_NOTHING2               1192
#define IDC_CHECK5                      1193
#define IDC_CHECK6                      1194
#define IDC_PREROLL                     1196
#define IDC_STALLTIME                   1197
#define IDC_STALLCOUNT                  1198
#define IDC_ERRORCOUNT                  1199
#define IDC_CANCEL                      1202
#define IDC_32x                         1203
#define IDC_GROUP1                      1204
#define IDC_GROUP2                      1205
#define IDC_GROUP3                      1206
#define IDC_GROUP6                      1207
#define IDC_GROUP7                      1208
#define IDC_GROUP9                      1209
#define IDC_NEW                         1211
#define IDC_RENAME                      1212
#define IDC_DELETE                      1213
#define IDC_PAUSE                       1214
#define IDC_LINK                        1216
#define IDC_ALIST                       1217
#define IDC_PLAY                        1218
#define IDC_ATYPE                       1219
#define IDC_AUTOPLAY                    1222
#define IDC_QTTIMESLIDER                1223
#define IDC_FIELD_QTNEXT                1224
#define IDC_QTCHAPTERMODE1              1225
#define IDC_QTCHAPTERMODE2              1226
#define IDC_IMMINST                     1227
#define ID_STATIC                       1229
#define IDC_BITRATELABEL                1229
#define IDC_BITRATENECESSARY            1230
#define ID_STATIC2                      1231
#define IDC_SYSTEMMIMELABEL             1231
#define IDC_SYSTEMMIMETYPE              1232
#define IDC_ATTACHTIMEBASE              1233
#define IDC_QTCHAPTER                   1234
#define ID_STATIC3                      1235
#define IDC_QTCHAPTERLABEL              1235
#define IDC_IMMINSTMEDIA1               1236
#define IDC_IMMINSTMEDIA2               1237
#define IDC_IMMINSTMEDIA3               1238
#define IDC_QTCOMPOSITEMODE             1239
#define IDC_FRAME1                      1240
#define IDC_FRAME2                      1241
#define ID_STATIC4                      1242
#define IDC_QTCOMPOSITELABEL            1242
#define IDC_LAYOUT_SCALE                1243
#define IDC_LAYOUT_PREVIEW              1244
#define IDC_LAYOUT_REGION_X             1246
#define IDC_LAYOUT_REGION_Y             1247
#define IDC_LAYOUT_REGION_W             1248
#define IDC_LAYOUT_REGION_H             1249
#define IDC_LAYOUT_REGION_Z             1250
#define IDC_LAYOUT_PROPERTIES           1251
#define IDC_LAYOUT_REGION_SEL           1252
#define IDC_LAYOUT_VIEWPORT_SEL         1253
#define IDC_LAYOUT_SHOW_NAMES           1254
#define IDC_PREVIOUS_AREA               1255
#define IDC_LAYOUT_SHOW_RBG             1256
#define IDC_SUBREG_Y                    1257
#define IDC_SUBREG_W                    1258
#define IDC_SUBREG_H                    1259
#define IDC_SUBREG_SHONLYREG            1260
#define IDC_SUBREG_FIT                  1261
#define IDC_LAYOUT_REGIONLIST           1262
#define IDC_LAYOUT_VIEWPORT_RADIO       1263
#define IDC_LAYOUT_REGION_RADIO         1264
#define IDC_LAYOUT_MEDIA_RADIO          1265
#define IDC_34x                         1267
#define IDC_SAUDIODESCV3                1268
#define IDC_CTYPES                      1270
#define IDC_CTYPET                      1271
#define IDC_CTYPEI                      1272
#define IDC_SHOWBACKGROUNDV1            1273
#define IDC_COLORS                      1274
#define IDC_COLOR_PICK                  1275
#define IDC_SHOWBACKGROUNDV2            1276
#define IDC_LABEL                       1277
#define IDC_LABEL2                      1278
#define IDC_OPENV1                      1278
#define IDC_SLIDER_POS                  1279
#define IDC_OPENV2                      1279
#define IDC_MIN                         1280
#define IDC_MAX                         1281
#define IDC_TREE_REGION1                1282
#define IDC_TREE1                       1283
#define IDC_LAYOUT_SHOW_ALLMEDIAS       1284
#define IDC_GROUP4                      1285
#define IDC_GROUP5                      1286
#define IDC_BUTTON2                     1288
#define IDC_BUTTON3                     1289
#define IDC_ADD                         1290
#define IDC_BUTTON6                     1291
#define IDC_EDIT                        1292
#define IDC_BUTTON9                     1293
#define IDC_STATIC2                     1294
#define IDC_EVENTCAUSE1                 1296
#define IDC_EVENTTYPE                   1297
#define IDC_EDIT11                      1298
#define IDC_TZHR                        1298
#define IDC_EDIT13                      1299
#define IDC_RESTARTNODEV                1299
#define IDC_81                          1300
#define IDC_RESTARTDEFAULTV             1300
#define IDC_LAYOUT_SHOW_ALLREGIONS      1301
#define IDC_LAYOUT_AS_OUTLINE           1302
#define IDC_SUBREG_X                    1303
#define IDC_LAYOUT_MEDIA_SEL            1304
#define IDC_LAYOUT_REGION_H2            1305
#define IDC_BUTTON5                     1306
#define IDC_BUTTON8                     1307
#define IDC_LIST4                       1308
#define IDC_RESTORE                     1309
#define IDC_MESSAGE2                    1310
#define IDC_7                           1311
#define IDC_33x                         1312
#define IDC_33                          1313
#define IDC_44                          1314
#define IDC_BUTTON_QTNEXT               1315
#define IDC_SAUDIODESCV2                1315
#define IDC_ADD_EXTERNAL                1316
#define IDC_SHOWHIDDENV2                1316
#define IDC_PROGRESS1                   1317
#define IDC_BUTTON7                     1318
#define IDC_PROMPT1                     1319
#define IDC_STOP                        1320
#define IDC_X                           1321
#define IDC_Y                           1322
#define IDC_W                           1323
#define IDC_H                           1324
#define IDC_Z                           1325
#define IDC_ZOOMIN                      1326
#define IDC_Z2                          1326
#define IDC_ZOOMOUT                     1327
#define IDC_THINGNAME                   1328
#define IDC_LAYOUT_REGION_FITL          1328
#define IDC_LAYOUT_FITL                 1328
#define IDC_THINGVALUE                  1329
#define IDC_EVENTLIST                   1332
#define IDC_NEWBUTTON                   1333
#define IDC_DELETEBUTTON                1334
#define IDC_RNODE                       1336
#define IDC_RDELAY                      1337
#define IDC_RLAYOUT                     1338
#define IDC_RINDEFINITE                 1339
#define IDC_RACCESSKEY                  1340
#define IDC_RWALLCLOCK                  1341
#define IDC_RMARKER                     1342
#define IDC_EDITOFFSET                  1343
#define IDC_EDITREPEAT                  1344
#define IDC_THINGBUTTON                 1345
#define IDC_EVENTTABNAME                1346
#define IDC_EVENTLASSOO                 1347
#define IDC_RADIO_ALL                   1348
#define IDC_EVENTLASSOO2                1348
#define IDC_RADIO_UNUSED                1349
#define IDC_RADIO_TEMPLATE              1349
#define IDC_RESULT                      1350
#define IDC_RADIO_CLIPBOARD             1350
#define IDC_YR                          1351
#define IDC_CBDATE                      1353
#define IDC_CBTZ                        1354
#define IDC_TZSG                        1355
#define IDC_MT                          1356
#define IDC_FILLL                       1357
#define IDC_FILLV                       1358
#define IDC_DURL                        1359
#define IDC_DURV                        1360
#define IDC_FILLDEFL                    1361
#define IDC_FILLDEFV                    1362
#define IDC_MINV                        1363
#define IDC_MINL                        1364
#define IDC_MAXV                        1365
#define IDC_MAXL                        1366
#define IDC_LOOPV                       1367
#define IDC_LOOPL                       1368
#define IDC_REPDURV                     1369
#define IDC_REPDURL                     1370
#define IDC_ENDSYNCV                    1371
#define IDC_ENDSYNCL                    1372
#define IDC_LEFTU                       1374
#define IDC_WIDTHU                      1375
#define IDC_RIGHTU                      1376
#define IDC_TOPU                        1377
#define IDC_HEIGHTU                     1378
#define IDC_BOTTOMU                     1379
#define IDC_LEFTL                       1380
#define IDC_WIDTHL                      1381
#define IDC_HEIGHTL                     1382
#define IDC_TOPL                        1383
#define IDC_RIGHTL                      1384
#define IDC_BOTTOML                     1385
#define IDC_LEFTV                       1386
#define IDC_FITV                        1388
#define IDC_REGALIGNV                   1390
#define IDC_REGALIGNL                   1391
#define IDC_REGPOINTV                   1392
#define IDC_REGPOINTL                   1393
#define IDC_FITL                        1394
#define IDC_ZL                          1395
#define IDC_SOUNDLEVELL                 1396
#define IDC_CLIPBEGINV                  1415
#define IDC_CLIPENDV                    1416
#define IDC_READINDEXV                  1417
#define IDC_EVENTSENSITIVITYV           1418
#define IDC_ERASEV1                     1419
#define IDC_ERASEV2                     1420
#define IDC_RESTARTNODEL                1421
#define IDC_RESTARTDEFAULTL             1422
#define IDC_SHOWBACKGROUNDL             1422
#define IDC_OPENL                       1423
#define IDC_CLOSEV1                     1424
#define IDC_CLOSEV2                     1425
#define IDC_CLOSEL                      1426
#define IDC_TRACEIMAGEL                 1427
#define IDC_TRACEIMAGEV                 1428
#define IDC_TRACEIMAGEB                 1429
#define IDC_IDL                         1430
#define IDC_IDV                         1431
#define IDC_NAMEL                       1432
#define IDC_REGIONIDL                   1432
#define IDC_NAMEV                       1433
#define IDC_REGIONIDV                   1433
#define IDC_REGIONNAMEL                 1434
#define IDC_TOPLAYOUTIDL                1434
#define IDC_REGIONNAMEV                 1435
#define IDC_TOPLAYOUTIDV                1435
#define IDC_REPEATLABEL                 1436
#define IDC_FINDNEXT                    1438
#define IDC_MATCHWHOLE                  1439
#define IDC_MATCHCASE                   1440
#define IDC_REPLACEWITH                 1441
#define IDC_REPLACE                     1442
#define IDC_FINDWHAT                    1443
#define IDC_AUTOWRAP                    1444
#define IDC_RELATIVE                    1446
#define IDC_STATIC_MSG                  1447
#define IDC_STATIC_MSG2                 1448
#define IDC_54                          1450
#define IDC_INIT_RECENT_COMBO           1451
#define IDC_SLIDER1                     1452
#define IDC_LAYOUT_SLIDER               1453
#define IDC_LAYOUT_FITV                 1454
#define IDC_ANIMATE_GROUP               1455
#define IDC_ANIMATE_P0L                 1456
#define IDC_ANIMATE_P100L               1457
#define IDC_ANIMATE_ENABLE              1458
#define IDC_ANIMATE_P50L                1459
#define IDC_PANEFOCUS                   1460
#define IDC_TREEFOCUS                   1461
#define IDC_IMMINSTLABEL                1461
#define IDC_QTNEXTLABEL                 1462
#define IDC_LATER                       1463
#define IDC_DONTREGISTER                1464
#define IDC_REGISTER                    1465
#define IDC_OL                          1466
#define IDC_OV                          1467
#define IDC_BGOL                        1468
#define IDC_MDOL                        1469
#define IDC_BGOV                        1470
#define IDC_MDOV                        1471
#define IDC_CKEYL                       1472
#define IDC_CKEYV                       1473
#define IDC_CKEYB                       1474
#define IDC_CKOV                        1475
#define IDC_CKOL                        1476
#define IDC_CKTL                        1477
#define IDC_RELIABLE                    1478
#define IDC_CKTV1                       1479
#define IDC_BITRL                       1480
#define IDC_NOTE                        1481
#define IDC_83                          1482
#define IDC_REGIONV                     1483
#define IDC_REGIONL                     1484
#define IDC_REGIONB                     1485
#define IDC_SENSITIVITYL                1486
#define IDC_SENSITIVITYV                1487
#define IDC_CLIPBL                      1488
#define IDC_CLIPBV                      1489
#define IDC_CLIPEL                      1490
#define IDC_CLIPEV                      1491
#define IDC_HIGHERL                     1492
#define IDC_PEERSL                      1493
#define IDC_LOWERL                      1494
#define IDC_PAUSEL                      1495
#define IDC_HIGHERV1                    1496
#define IDC_HIGHERV2                    1497
#define IDC_PEERSV1                     1498
#define IDC_PEERSV2                     1499
#define IDC_PEERSV3                     1500
#define IDC_PEERSV4                     1501
#define IDC_LOWERV1                     1502
#define IDC_LOWERV2                     1503
#define IDC_PAUSEV1                     1504
#define IDC_PAUSEV2                     1505
#define IDC_PAUSEV3                     1506
#define IDC_ATAGV                       1508
#define IDC_ATAGL                       1509
#define IDC_ATYPEV1                     1510
#define IDC_ATYPEV2                     1511
#define IDC_ATYPEV3                     1512
#define IDC_ATYPEL                      1513
#define IDC_TELEML                      1514
#define IDC_TATTRL                      1515
#define IDC_TELEMV                      1516
#define IDC_TELEMB                      1517
#define IDC_TATTRV                      1518
#define IDC_ORIGINL                     1519
#define IDC_ORIGINV1                    1520
#define IDC_ORIGINV2                    1521
#define IDC_PATHL                       1522
#define IDC_PATHV                       1523
#define IDC_TOL                         1524
#define IDC_TOV                         1525
#define IDC_FROML                       1526
#define IDC_FROMV                       1527
#define IDC_BYL                         1528
#define IDC_BYV                         1529
#define IDC_VALUESL                     1530
#define IDC_ADDITIVEL                   1531
#define IDC_ACCUMULATEL                 1532
#define IDC_ADDITIVEV1                  1533
#define IDC_ADDITIVEV2                  1534
#define IDC_ACCUMULATEV1                1535
#define IDC_ACCUMULATEV2                1536
#define IDC_SENDTOV                     1537
#define IDC_ACOORDSL                    1538
#define IDC_ACOORDSV                    1539
#define IDC_FRAGMENTL                   1540
#define IDC_FRAGMENTV                   1541
#define IDC_ACCESSL                     1542
#define IDC_ACCESSV                     1543
#define IDC_TABINDEXL                   1544
#define IDC_ASHAPEL                     1545
#define IDC_ASHAPEV                     1546
#define IDC_ACTUATEV                    1547
#define IDC_SENDTOL                     1548
#define IDC_ACTUATEL                    1549
#define IDC_COMBO3                      1551
#define IDC_STATIC3                     1552
#define IDC_STATIC4                     1553
#define IDC_COMBO4                      1554
#define IDC_STATIC5                     1555
#define IDC_STATIC0                     1556
#define IDC_STATIC7                     1557
#define IDC_STATIC8                     1558
#define IDC_STATIC9                     1559
#define IDC_STATIC6                     1560
#define IDC_COMBO5                      1561
#define IDC_TOLLABEL                    1562
#define IDC_TOLVALUE                    1563
#define ID_FILE_NEW_GRINS               32771
#define ID_FILE_OPEN_GRINS              32772
#define ID_FILE_SAVE_GRINS              32773
#define ID_FILE_SAVE_AS_GRINS           32774
#define ID_GRINS_EXIT                   32775
#define ID_EDIT_UNDO_GRINS              32776
#define ID_EDIT_CUT_GRINS               32777
#define ID_EDIT_COPY_GRINS              32778
#define ID_EDIT_PASTE_GRINS             32779
#define ID_GRINS_ABOUT                  32780
#define ID_BUTTON32785                  32785
#define ID_BUTTON32786                  32786
#define ID_BUTTON32787                  32787
#define ID_PRINTDOC                     32788
#define ID_BUTTON32790                  32790
#define IDUC_NEW_DOCUMENT               32800
#define IDUC_OPEN                       32801
#define IDUC_SAVE                       32802
#define IDUC_RESTORE                    32803
#define IDUC_CLOSE                      32804
#define IDUC_PLAY                       32805
#define IDUC_PAUSE                      32806
#define IDUC_STOP                       32807
#define IDUC_HELP                       32808
#define IDUC_CLOSE_WINDOW               32811
#define IDUC_PASTE                      32812
#define IDUC_UNDO                       32813
#define IDUC_CUT                        32814
#define IDUC_COPY                       32815
#define IDUC_MAGIC_PLAY                 32818
#define IDUC_HVIEW                      32819
#define IDUC_PLAYER                     32820
#define IDUC_LAYOUT                     32821
#define IDUC_CVIEW                      32822
#define IDUC_HLINKS                     32823
#define IDUC_SOURCE                     32824
#define IDUC_UGROUPS                    32825
#define IDUC_PASTEFILE                  32827
#define IDUC_OPENURL                    32828
#define IDUC_PLAYNODE                   32829
#define ID_ACCEL32830                   32830
#define IDUC_INFO                       32831
#define IDUC_ATTRIBUTES                 32832
#define IDUC_TOPARENT                   32833
#define IDUC_PREVSIBLING                32834
#define IDUC_NEXTSIBLING                32836
#define IDUC_TOCHILD                    32837
#define ID_ACCEL32838                   32838
#define IDUC_EXPAND                     32839
#define ID_U                            32840
#define ID_G                            32841
#define ID_T                            32842
#define ID_I                            32843
#define ID_L                            32844
#define ID_S                            32845
#define ID_O                            32846
#define ID_F                            32848
#define ID_Z                            32849
#define ID_N                            32850
#define ID_A                            32851
#define ID_Q                            32852
#define ID_D                            32853
#define ID_R                            32854
#define ID_V                            32855
#define ID_K                            32856
#define ID_C                            32857
#define ID_E                            32858
#define ID_M                            32859
#define IDUC_CANVAS_ZOOM_IN             32860
#define IDUC_CANVAS_ZOOM_OUT            32862
#define DUC_CANVAS_ZOOM_IN              32863
#define UC_CANVAS_ZOOM_OUT              32864
#define IDUC_REDO                       32865
#define IDUC_ALIGN_LEFT                 32869
#define IDUC_ALIGN_CENTER               32870
#define IDUC_ALIGN_RIGHT                32871
#define IDUC_ALIGN_TOP                  32872
#define IDUC_ALIGN_MIDDLE               32873
#define IDUC_ALIGN_BOTTOM               32874
#define IDUC_DISTRIBUTE_HORIZONTALLY    32875
#define IDUC_DISTRIBUTE_VERTICALLY      32876
#define IDUC_CREATE_ANCHOR              32877
#define IDUC_FINISH_LINK                32878
#define IDUC_PAR                        32880
#define IDUC_SEQ                        32881
#define IDUC_SWITCH                     32883
#define IDUC_EXCL                       32884
#define IDUC_PRIO                       32885
#define IDUC_CREATE_EVENT               32886
#define IDUC_BEGIN_EVENT                32887
#define IDUC_END_EVENT                  32888
#define IDUC_EVENT_SOURCE               32889
#define IDUC_FIND                       32890
#define IDUC_REPLACE                    32891
#define IDUC_FINDNEXT                   32892
#define IDUC_MEDIA                      32895
#define IDUC_ANIMATE                    32896
#define IDUC_BRUSH                      32897
#define IDUC_REGION                     32898
#define IDUC_TOPLAYOUT                  32899
#define IDUC_ZOOMIN                     32900
#define IDUC_ZOOMOUT                    32901
#define IDUC_CREATE_ANCHOREXTENDED      32902
#define IDUC_CREATE_ANCHOR_CONTEXT      32903
#define IDUC_CREATE_ANCHOR_BROWSER      32904
#define IDUC_MARK                       32905
#define IDUC_ZOOMRESET                  32906

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        489
#define _APS_NEXT_COMMAND_VALUE         32907
#define _APS_NEXT_CONTROL_VALUE         1564
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
