//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GRiNSRes.rc
//
#define IDS_ABOUTBOX                    101
#define IDD_GRINSEDBAR                  130
#define IDC_POINT_HAND                  141
#define IDD_CREATE_BOX                  147
#define IDD_SPLASH                      157
#define IDI_GRINS_ED                    198
#define IDD_DIALOG_OPENLOCATION         199
#define IDR_GRINSED                     200
#define IDD_LAYOUT                      201
#define IDD_NEW_CHANNEL                 202
#define IDD_LAYOUT_NAME                 203
#define IDD_FORM                        204
#define IDD_LAYOUT1                     205
#define IDD_EDITSTRINGATTR              206
#define IDD_EDITOPTIONSATTR             207
#define IDD_EDITFILEATTR                208
#define IDD_STDDLGBAR                   209
#define IDD_EDIT_ANCHOR_BAR             210
#define IDD_ANCHOR_BAR                  211
#define IDD_NODE_INFO_CMDBAR            212
#define IDD_NODE_INFO_BAR               213
#define IDD_LINKS                       214
#define IDD_OKCANCELBARV                215
#define IDD_ARC_INFO_BAR                216
#define IDD_EXT_GROUP                   217
#define IDD_SELECT_ONE                  218
#define IDD_INT_GROUP                   219
#define IDD_IMM_GROUP                   220
#define IDD_MESSAGE_BOX                 221
#define IDD_OKCANCELBARH                222
#define IDD_PREFERENCES                 223
#define IDD_CREATE_BOX1                 224
#define IDD_ABOUT                       225
#define IDB_SPLASH                      226
#define IDD_EDIT_USERGROUP              227
#define IDD_USERGROUP                   228
#define IDR_GRINS                       229
#define IDD_LINK_PROPERTY               230
#define IDI_CREATE_BOX                  231
#define IDD_USERGROUP1                  231
#define IDD_LAYOUT2                     231
#define IDD_EDIT_ANCHORS                232
#define IDC_STOP                        233
#define IDD_ARC_INFO_FORM               233
#define IDD_NODE_INFO                   234
#define IDC_DRAGMOVE                    237
#define IDC_DRAGLINK                    238
#define IDC_PLAY                        1001
#define IDC_PAUSE                       1002
#define IDC_PLAYER                      1010
#define IDC_LIST2                       1018
#define IDC_BUTTON_BROWSE               1019
#define IDC_EDIT_LOCATION               1020
#define IDC_TAB_GRINSVIEWS              1021
#define IDCMD_NEW_LAYOUT                1022
#define IDCMD_RENAME                    1023
#define IDC_SPLASH                      1023
#define IDCMD_DELETE                    1024
#define IDC_LAYOUTS                     1025
#define IDC_CHANNEL_NAME                1026
#define IDC_CHANNEL_TYPE                1027
#define IDC_EDIT1                       1028
#define IDCMD_NEW_CHANNEL               1030
#define IDCMD_REMOVE_CHANNEL            1031
#define IDCMD_ATTRIBUTES                1032
#define IDC_LAYOUT_CHANNELS             1033
#define IDC_EDIT2                       1033
#define IDCMD_ADD_CHANNEL               1034
#define IDC_COMBO1                      1034
#define IDC_COMBO2                      1035
#define IDUC_APPLY                      1036
#define IDC_OTHER_CHANNELS              1037
#define IDUC_RESET                      1043
#define IDUC_BROWSE                     1044
#define IDC_STATIC1                     1045
#define IDUC_NEW                        1046
#define IDUC_EDIT                       1047
#define IDUC_DELETE                     1048
#define IDUC_EXPORT                     1049
#define IDUC_NODE_ATTRIBUTES            1051
#define IDUC_CHANNEL_ATTRIBUTES         1052
#define IDUC_ANCHORS                    1053
#define IDUC_CANCEL                     1054
#define IDUC_OK                         1055
#define IDC_PUSH_FOCUS1                 1056
#define IDC_ANCHOR_EDITOR1              1057
#define IDC_PUSH_FOCUS2                 1058
#define IDC_ANCHOR_EDITOR2              1059
#define IDC_ADD_LINK                    1060
#define IDC_EDIT_LINK                   1061
#define IDC_DELETE_LINK                 1062
#define IDC_RADIO1                      1063
#define IDC_RADIO2                      1064
#define IDC_RADIO3                      1065
#define IDC_RADIO4                      1067
#define IDC_RADIO5                      1068
#define IDC_RADIO6                      1069
#define IDC_LIST1                       1072
#define IDC_LEFT_MENU                   1074
#define IDC_RIGHT_MENU                  1075
#define IDC_STATIC_LEFT                 1076
#define IDC_STATIC_RIGHT                1077
#define IDC_OPENCHILD                   1078
#define IDC_RESTORE                     1078
#define IDC_LIST_LINKS                  1080
#define IDC_RESET                       1081
#define IDC_CHECK1                      1082
#define IDC_CHECK2                      1083
#define IDC_NODE_TYPE                   1085
#define IDC_NODE_NAME                   1088
#define IDC_CHANNEL                     1089
#define IDC_EXT_EDIT                    1090
#define IDC_IMM_EDIT                    1091
#define IDC_INT_LIST                    1092
#define IDCMD_CLOSE_WINDOW              1093
#define IDC_CANCEL                      1094
#define IDC_OK                          1095
#define IDC_MESSAGE                     1097
#define IDC_VERSION_MSG                 1098
#define IDC_LINK_D                      1099
#define IDC_LINK_T                      1100
#define IDCMD_NEW_GROUP                 1101
#define IDCMD_EDIT_GROUP                1102
#define IDC_GROUPS                      1103
#define IDC_APPLY                       1104
#define IDCMD_DELETE_GROUP              1105
#define IDCMD_CLOSE_USERGROUPVIEW       1106
#define IDC_CHECK3                      1107
#define IDC_CHECK4                      1108
#define IDC_EDIT                        1110
#define IDC_CUSTOM1                     1113
#define ID_FILE_NEW_GRINS               32771
#define ID_FILE_OPEN_GRINS              32772
#define ID_FILE_SAVE_GRINS              32773
#define ID_FILE_SAVE_AS_GRINS           32774
#define ID_GRINS_EXIT                   32775
#define ID_EDIT_UNDO_GRINS              32776
#define ID_EDIT_CUT_GRINS               32777
#define ID_EDIT_COPY_GRINS              32778
#define ID_EDIT_PASTE_GRINS             32779
#define ID_GRINS_ABOUT                  32780
#define ID_BUTTON32785                  32785
#define ID_BUTTON32786                  32786
#define ID_BUTTON32787                  32787
#define ID_BUTTON32788                  32788
#define ID_PRINTDOC                     32788
#define ID_BUTTON32790                  32790
#define IDUC_NEW_DOCUMENT               32800
#define IDUC_OPEN                       32801
#define IDUC_SAVE                       32802
#define IDUC_RESTORE                    32803
#define IDUC_CLOSE                      32804
#define IDUC_PLAY                       32805
#define IDUC_PAUSE                      32806
#define IDUC_STOP                       32807
#define IDUC_HELP                       32808
#define IDUC_CLOSE_WINDOW               32811
#define IDUC_PASTE                      32812
#define IDUC_UNDO                       32813
#define IDUC_CUT                        32814
#define IDUC_COPY                       32815
#define IDUC_MAGIC_PLAY                 32818
#define IDUC_HVIEW                      32819
#define IDUC_PLAYER                     32820
#define IDUC_LAYOUT                     32821
#define IDUC_CVIEW                      32822
#define IDUC_HLINKS                     32823
#define IDUC_SOURCE                     32824
#define IDUC_UGROUPS                    32825

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        239
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
