__version__ = "$Id$"

#
# This file should be updated whenever you update any of
# the toolbars in the GRiNSRes file.
#

# Icon indices in the IDR_TB_COMMON toolbar
TBICON_NEW=0
TBICON_OPENFILE=1
TBICON_SAVE=2
TBICON_CLOSE=3
TBICON_CLOSE_WINDOW=4
TBICON_RESTORE=5
TBICON_PLAY=6
TBICON_PAUSE=7
TBICON_STOP=8
TBICON_HELP=9
TBICON_ZOOMIN=10
TBICON_ZOOMOUT=11
TBICON_ZOOMRESET=12

# Icon indices in the IDR_TB_EDITOR toolbar
TBICON_CUT=0
TBICON_COPY=1
TBICON_PASTE=2
TBICON_ALIGN_LEFT=3
TBICON_ALIGN_VERTICAL=4
TBICON_ALIGN_RIGHT=5
TBICON_ALIGN_TOP=6
TBICON_ALIGN_HORIZONTAL=7
TBICON_ALIGN_BOTTOM=8
TBICON_DISTRIBUTE_HORIZONTAL=9
TBICON_DISTRIBUTE_VERTICAL=10
TBICON_CREATE_ANCHOR=11
TBICON_FINISH_LINK=12
TBICON_PAR=13
TBICON_SEQ=14
TBICON_SWITCH=15
TBICON_EXCL=16
TBICON_PRIO=17
TBICON_EVENT_SOURCE=18
TBICON_BEGIN_EVENT=19
TBICON_END_EVENT=20
TBICON_MEDIA=21
TBICON_ANIMATE=22
TBICON_BRUSH=23
TBICON_REGION=24
TBICON_TOPLAYOUT=25
TBICON_CREATE_ANCHOREXTENDED=26
TBICON_CREATE_ANCHOR_CONTEXT=27
TBICON_CREATE_ANCHOR_BROWSER=28
