
import "oaidl.idl";
import "ocidl.idl";


[
	object,
	uuid(698A27F32-35E3-4313-9EA5-9D66B691032E),
	helpstring("IGRiNSPlayer Interface"),
	pointer_default(unique)
]

interface IGRiNSPlayer : IUnknown
{
	HRESULT Open([in, string] wchar_t *szName);
	HRESULT Play();
	HRESULT Stop();
	HRESULT Pause();
	HRESULT OnEvent([in, string] wchar_t *szEventVar);
	HRESULT SetAttribute([in, string] wchar_t *szName,[in] VARIANT varValue);
};

