__version__ = "$Id$"

EVALcomment = ' Created with an evaluation copy of GRiNS '
SMIL_BASIC = 'text/smil-basic-layout'

SMIL10Pubid = '-//W3C//DTD SMIL 1.0//EN'
SMIL10 = 'http://www.w3.org/TR/REC-smil'
SMIL10Dtd = SMIL10 + '/SMIL10.dtd'

SMIL20Pubid = '-//W3C//DTD SMIL 2.0//EN'
SMIL20 = 'http://www.w3.org/2001/SMIL20/'
SMIL20Dtd = SMIL20 + 'SMIL20.dtd'

SMIL21Pubid = '-//W3C//DTD SMIL 2.1//EN'
SMIL21 = 'http://www.w3.org/2005/SMIL21/'
SMIL21Dtd = SMIL21 + 'SMIL21.dtd'

SMIL30Pubid = '-//W3C//DTD SMIL 3.0 Language//EN'
SMIL30 = 'http://www.w3.org/2007/07/SMIL30/'
SMIL30Dtd = SMIL30 + 'SMIL30Language.dtd'

DOCTYPES = {
    # PUBID : ( SYSLIT, profile, version)
    '-//W3C//DTD SMIL 3.0 Language//EN': ('http://www.w3.org/2007/SMIL30/SMIL30Language.dtd', 'Language', 30),
    '-//W3C//DTD SMIL 3.0 Daisy//EN': ('http://www.w3.org/2007/SMIL30/SMIL30Daisy.dtd', 'Daisy', 30),
    '-//W3C//DTD SMIL 3.0 Extended Mobile//EN': ('http://www.w3.org/2007/SMIL30/SMIL30ExtendedMobile.dtd', 'Extended Mobile', 30),
    '-//W3C//DTD SMIL 3.0 Mobile//EN': ('http://www.w3.org/2007/SMIL30/SMIL30Mobile.dtd', 'Mobile', 30),
    '-//W3C//DTD SMIL 3.0 Tiny//EN': ('http://www.w3.org/2007/SMIL30/SMIL30Tiny.dtd', 'Tiny', 30),
    '-//W3C//DTD SMIL 2.1//EN': ('http://www.w3.org/2005/SMIL21/SMIL21.dtd', 'Language', 21),
    '-//W3C//DTD SMIL 2.1 Extended Mobile//EN': ('http://www.w3.org/2005/SMIL21/SMIL21ExtendedMobile.dtd', 'Extended Mobile', 21),
    '-//W3C//DTD SMIL 2.1 Mobile//EN': ('http://www.w3.org/2005/SMIL21/SMIL21Mobile.dtd', 'Mobile', 21),
    '-//W3C//DTD SMIL 2.0//EN': ('http://www.w3.org/2001/SMIL20/SMIL20.dtd', 'Language', 20),
    '-//W3C//DTD SMIL 1.0//EN': ('http://www.w3.org/TR/REC-smil/SMIL10.dtd', None, 10),
    }

# namespaces recognized by GRiNS
# the first one is the required default namespace, but SMIL10
# doesn't generate a warning
SMIL20ns = ['http://www.w3.org/2001/SMIL20/Language',
            'http://www.w3.org/2001/SMIL20/']
SMIL21ns = ['http://www.w3.org/2005/SMIL21/Language',
            'http://www.w3.org/2005/SMIL21/ExtendedMobile',
            'http://www.w3.org/2005/SMIL21/Mobile',
            'http://www.w3.org/2005/SMIL21/']
SMIL30ns = ['http://www.w3.org/ns/SMIL']
GRiNSns = 'http://www.oratrix.com/'
RP9ns = 'http://features.real.com/2001/SMIL20/Extensions'
QTns = 'http://www.apple.com/quicktime/resources/smilextensions'
PSS4ns = 'http://www.3gpp.org/SMIL20/PSS4/'
PSS5ns = 'http://www.3gpp.org/SMIL20/PSS5/'
ITSns = 'http://www.w3.org/2005/11/its'
XHTMLns = 'http://www.w3.org/1999/xhtml'

# list elements here that are not valid in all namespaces with the
# namespaces they are valid in
limited = {
    'paramGroup': SMIL21ns[:3],
        }

_refelems = ['ref', 'animation', 'audio', 'img', 'text', 'textstream', 'video']
ATTRIBUTES = {
    'abstract': ['MediaDescription'],
    'accelerate': ['TimeManipulations'],
    'accesskey': ['LinkingAttributes'],
    'accumulate': ['BasicAnimation'],
    'action': ['StateSubmission'],
    'actuate': ['LinkingAttributes'],
    'additive': ['BasicAnimation'],
    'allowReorder': ['BasicContentControl'],
    'alt': ['MediaAccessibility'],
    'attributeName': ['BasicAnimation'],
    'attributeType': ['BasicAnimation'],
    'author': ['MediaDescription'],
    'autoReverse': ['TimeManipulations'],
    'background-color': ['BasicLayout'],
    'backgroundColor': {'BasicLayout': ['region', 'root-layout'],
                        'MultiWindowLayout': ['topLayout'],
                        'HierarchicalLayout': _refelems,
                        'OverrideLayout': _refelems},
    'backgroundImage': ['BackgroundTilingLayout'],
    'backgroundOpacity': ['BasicLayout'],
    'backgroundRepeat': ['BackgroundTilingLayout'],
    'bandwidth': ['PrefetchControl'],
    'baseProfile': ['Identity'],
    'begin': {'AccessKeyTiming': None,
              'EventTiming': None,
              'MediaMarkerTiming': None,
              'MultiArcTiming': None,
              'RepeatValueTiming': None,
              'BasicInlineTiming': None,
              'SyncbaseTiming': None,
              'WallclockTiming': None,
              'InlineTransitions': ['transitionFilter']},
    'borderColor': ['TransitionModifiers'],
    'borderWidth': ['TransitionModifiers'],
    'bottom': {'BasicLayout': ['region'],
               'HierarchicalLayout': _refelems + ['brush'],
               'SubRegionLayout': _refelems + ['brush']},
    'by': {'BasicAnimation': None,
           'InlineTransitions': ['transitionFilter']},
    'calcMode': {'BasicAnimation': None,
                 'SplineAnimation': None,
                 'InlineTransitions': ['transitionFilter']},
    'chromaKey': ['MediaOpacity'],
    'chromaKeyOpacity': ['MediaOpacity'],
    'chromaKeyTolerance': ['MediaOpacity'],
    'class': ['Structure'],
    'clip-begin': ['MediaClipping', 'MediaClipMarkers'],
    'clip-end': ['MediaClipping', 'MediaClipMarkers'],
    'clipBegin': ['MediaClipping', 'MediaClipMarkers'],
    'clipEnd': ['MediaClipping', 'MediaClipMarkers'],
    'close': ['MultiWindowLayout'],
    'color': ['BrushMedia'],
    'content': ['Metainformation'],
    'coords': ['BasicLinking'],
    'copyright': ['MediaDescription'],
    'customTest': ['CustomTestAttributes'],
    'decelerate': ['TimeManipulations'],
    'defaultState': ['CustomTestAttributes'],
    'destinationLevel': ['LinkingAttributes'],
    'destinationPlaystate': ['LinkingAttributes'],
    'direction': ['BasicTransitions'],
    'dur': {'BasicInlineTiming': ['a','animate','set','animateMotion',
                                  'animateColor','area','anchor',
                                  'transitionFilter','brush','body','par',
                                  'seq','excl','prefetch','send',
                                  'newvalue','delvalue','setvalue'] + _refelems,
            'BasicTransitions': ['transition'],
            'InlineTransitions': ['transitionFilter']},
    'end': {'AccessKeyTiming': None,
            'EventTiming': None,
            'MediaMarkerTiming': None,
            'MultiArcTiming': None,
            'RepeatValueTiming': None,
            'BasicInlineTiming': None,
            'SyncbaseTiming': None,
            'WallclockTiming': None,
            'InlineTransitions': ['transitionFilter']},
    'endProgress': ['BasicTransitions'],
    'endsync': {'ExclTimeContainers': ['excl'],
                'BasicExclTimeContainers': ['excl'],
                'TimeContainerAttributes': None,
                'BasicTimeContainers': None},
    'erase': ['MediaParam'],
    'expr': ['StateTest'],
    'external': ['LinkingAttributes'],
    'fadeColor': {'BasicTransitions': None,
                  'InlineTransitions': ['transitionFilter']},
    'fill': {'ExclTimeContainers': ['excl'],
             'BasicExclTimeContainers': ['excl'],
             'TimeContainerAttributes': None,
             'BasicTimeContainers': None},
    'fillDefault': ['FillDefault'],
    'fit': {'BasicLayout': ['region'],
            'HierarchicalLayout': _refelems + ['brush'],
            'OverrideLayout': _refelems + ['brush']},
    'fragment': ['ObjectLinking'],
    'from': {'BasicAnimation': None,
             'InlineTransitions': ['transitionFilter']},
    'height': {'BasicLayout': ['region', 'root-layout'],
               'MultiWindowLayout': ['topLayout'],
               'HierarchicalLayout': _refelems + ['brush'],
               'SubRegionLayout': _refelems + ['brush']},
    'higher': ['ExclTimeContainers', 'BasicPriorityClassContainers'],
    'horzRepeat': ['TransitionModifiers'],
    'href': ['BasicLinking'],
    'id': ['Structure'],
    'keySplines': ['SplineAnimation'],
    'keyTimes': ['SplineAnimation'],
    'label': ['Metainformation'],
    'language': ['UserState'],
    'left': {'BasicLayout': ['region'],
             'HierarchicalLayout': _refelems + ['brush'],
             'SubRegionLayout': _refelems + ['brush']},
    'longdesc': ['MediaAccessibility'],
    'lower': ['ExclTimeContainers', 'BasicPriorityClassContainers'],
    'max': ['MinMaxTiming'],
    'mediaAlign': ['AlignmentLayout'],
    'mediaBackgroundOpacity': ['MediaOpacity'],
    'mediaOpacity': ['MediaOpacity'],
    'mediaRepeat': ['MediaParam'],
    'mediaSize': ['PrefetchControl'],
    'mediaTime': ['PrefetchControl'],
    'method': ['StateSubmission'],
    'min': ['MinMaxTiming'],
    'mode': ['InlineTransitions'],
    'name': {'MediaParam': ['param'],
             'Metainformation': ['meta'],
             'UserState': ['newvalue']},
    'next': ['BasicText'],
    'nohref': ['BasicLinking'],
    'open': ['MultiWindowLayout'],
    'origin': ['BasicAnimation'],
    'override': ['CustomTestAttributes'],
    'panZoom': ['MediaPanZoom'],
    'paramGroup': ['MediaParam'],
    'path': ['SplineAnimation'],
    'pauseDisplay': ['ExclTimeContainers', 'BasicPriorityClassContainers'],
    'peers': ['ExclTimeContainers', 'BasicPriorityClassContainers'],
    'readIndex': ['MediaAccessibility'],
    'regAlign': ['HierarchicalLayout', 'AlignmentLayout'],
    'regPoint': ['HierarchicalLayout', 'AlignmentLayout'],
    'region': ['BasicLayout'],
    'regionName': ['BasicLayout'],
    'repeat': ['RepeatTiming'],
    'repeatCount': {'RepeatTiming': None,
                    'InlineTransitions': ['inlineTransition']},
    'repeatDur': {'RepeatTiming': None,
                  'InlineTransitions': ['inlineTransition']},
    'replace': ['StateSubmission'],
    'restart': ['RestartTiming'],
    'restartDefault': ['RestartDefault'],
    'right': {'BasicLayout': ['region'],
              'HierarchicalLayout': _refelems + ['brush'],
              'SubRegionLayout': _refelems + ['brush']},
    'scope': ['FullScreenTransitionEffects'],
    'sensitivity': ['MediaParam'],
    'shape': ['BasicLinking'],
    'show': ['LinkingAttributes'],
    'showBackground': ['BasicLayout'],
    'skip-content': ['SkipContentControl'],
    'soundAlign': ['AlignmentLayout'],
    'soundLevel': ['AudioLayout'],
    'sourceLevel': ['LinkingAttributes'],
    'sourcePlaystate': ['LinkingAttributes'],
    'speed': ['TimeManipulations'],
    'src': ['BasicMedia'],
    'startProgress': ['BasicTransitions'],
    'submission': ['StateSubmission'],
    'subtype': {'BasicTransitions': None,
                'InlineTransitions': ['inlineTransition']},
    'syncBehavior': ['SyncBehavior'],
    'syncBehaviorDefault': ['SyncBehaviorDefault'],
    'syncMaster': ['SyncMaster'],
    'syncTolerance': ['SyncBehavior'],
    'syncToleranceDefault': ['SyncBehaviorDefault'],
    'system-bitrate': ['BasicContentControl'],
    'system-captions': ['BasicContentControl'],
    'system-language': ['BasicContentControl'],
    'system-overdub-or-caption': ['BasicContentControl'],
    'system-required': ['BasicContentControl', 'RequiredContentControl'],
    'system-screen-depth': ['BasicContentControl'],
    'system-screen-size': ['BasicContentControl'],
    'systemAudioDesc': ['BasicContentControl'],
    'systemBaseProfile': ['BasicContentControl'],
    'systemBitrate': ['BasicContentControl'],
    'systemCPU': ['BasicContentControl'],
    'systemCaptions': ['BasicContentControl'],
    'systemComponent': ['BasicContentControl'],
    'systemLanguage': ['BasicContentControl'],
    'systemOperatingSystem': ['BasicContentControl'],
    'systemOverdubOrSubtitle': ['BasicContentControl'],
    'systemRequired': ['BasicContentControl', 'RequiredContentControl'],
    'systemScreenDepth': ['BasicContentControl'],
    'systemScreenSize': ['BasicContentControl'],
    'systemVersion': ['BasicContentControl'],
    'tabindex': ['LinkingAttributes'],
    'target': ['LinkingAttributes'],
    'targetElement': {'BasicAnimation': None,
                      'InlineTransitions': ['inlineTransition']},
    'textAlign': {'BasicText': ['smilText'],
                  'TextStyling': ['div', 'textStyle']},
    'textBackgroundColor': ['TextStyling'],
    'textColor': ['TextStyling'],
    'textConceal': ['TextMotion'],
    'textDirection': ['TextStyling'],
    'textFontFamily': ['TextStyling'],
    'textFontSize': ['TextStyling'],
    'textFontStyle': ['TextStyling'],
    'textFontWeight': ['TextStyling'],
    'textMode': ['TextStyling'],
    'textPlace': ['TextStyling'],
    'textRate': ['TextMotion'],
    'textStyle': ['TextStyling'],
    'textWrapOption': ['BasicText'],
    'textWritingMode': ['TextStyling'],
    'timeAction': ['TimeContainerAttributes'],
    'timeContainer': ['TimeContainerAttributes'],
    'title': ['Structure', 'MediaDescription'],
    'to': {'BasicAnimation': None,
           'InlineTransitions': ['inlineTransition']},
    'top': {'BasicLayout': ['region'],
            'HierarchicalLayout': _refelems + ['brush'],
            'SubRegionLayout': _refelems + ['brush']},
    'transIn': ['BasicTransitions'],
    'transOut': ['BasicTransitions'],
    'type': {'BasicLayout': ['layout'],
             'BasicMedia': _refelems,
             'MediaParam': ['param'],
             'BasicTransitions': ['transition'],
             'InlineTransitions': ['transitionFilter']},
    'uid': ['CustomTestAttributes'],
    'value': {'MediaParam': None,
              'UserState': ['setvalue', 'newvalue']},
    'values': {'BasicAnimation': None,
               'InlineTransitions': ['transitionFilter']},
    'valuetype': ['MediaParam'],
    'version': ['Identity'],
    'vertRepeat': ['TransitionModifiers'],
    'where': ['UserState'],
    'width': {'BasicLayout': ['region', 'root-layout'],
              'MultiWindowLayout': ['topLayout'],
              'HierarchicalLayout': _refelems + ['brush'],
              'SubRegionLayout': _refelems + ['brush']},
    'xml:id': ['Structure'],
    'xml:lang': ['Structure', 'MediaDescription'],
    'xmlns': ['Structure'],
    'xml:space': ['BasicText'],
    'z-index': {'BasicLayout': ['region'],
                'HierarchicalLayout': _refelems + ['brush'],
                'OverrideLayout': _refelems + ['brush']},
    }

ELEMENTS = {
    'a': ['BasicLinking'],
    'anchor': ['BasicLinking'],
    'animate': ['BasicAnimation'],
    'animateColor': ['BasicAnimation'],
    'animateMotion': ['BasicAnimation'],
    'animation': ['BasicMedia'],
    'area': ['BasicLinking'],
    'audio': ['BasicMedia'],
    'body': ['Structure'],
    'br': ['BasicText'],
    'brush': ['BrushMedia'],
    'clear': ['BasicText'],
    'customAttributes': ['CustomTestAttributes'],
    'customTest': ['CustomTestAttributes'],
    'delvalue': ['UserState'],
    'div': ['TextStyling'],
    'excl': ['ExclTimeContainers', 'BasicExclTimeContainers'],
    'head': ['Structure'],
    'img': ['BasicMedia'],
    'layout': ['BasicLayout', 'StructureLayout'],
    'meta': ['Metainformation'],
    'metadata': ['Metainformation'],
    'newvalue': ['UserState'],
    'p': ['TextStyling'],
    'par': ['BasicTimeContainers'],
    'param': ['MediaParam'],
    'paramGroup': ['MediaParam'],
    'prefetch': ['PrefetchControl'],
    'priorityClass': ['ExclTimeContainers', 'BasicPriorityClassContainers'],
    'ref': ['BasicMedia'],
    'regPoint': ['HierarchicalLayout', 'AlignmentLayout'],
    'region': ['BasicLayout'],
    'root-layout': ['BasicLayout'],
    'send': ['StateSubmission'],
    'seq': ['BasicTimeContainers'],
    'set': ['BasicAnimation'],
    'setvalue': ['UserState'],
    'smil': ['Structure'],
    'smilText': ['BasicText'],
    'span': ['TextStyling'],
    'state': ['UserState'],
    'submission': ['StateSubmission'],
    'switch': ['BasicContentControl'],
    'tev': ['BasicText'],
    'text': ['BasicMedia'],
    'textStyle': ['TextStyling'],
    'textStyling': ['TextStyling'],
    'textstream': ['BasicMedia'],
    'topLayout': ['MultiWindowLayout'],
    'transition': ['BasicTransitions'],
    'transitionFilter': ['InlineTransitions'],
    'video': ['BasicMedia'],
    }

class SMIL:
    # some abbreviations
    __layouts = GRiNSns + ' ' + 'layouts'
    __layout = GRiNSns + ' ' + 'layout'
    __assets = GRiNSns + ' ' 'assets'
    __viewinfo = GRiNSns + ' ' 'viewinfo'

    # abbreviations for collections of attributes
    __Core = {'alt':None,
              'baseProfile':None,
              'class':None,
              'id':None,
              'label':None,
              'longdesc':None,
              'readIndex':None,
              'title':None,
              'version':None,
              'xml:base':None,
              'xml:id':None,}
    __I18n = {'xml:lang':None,
              ITSns+' '+'dir':None,
              ITSns+' '+'locNote':None,
              ITSns+' '+'locNoteRef':None,
              ITSns+' '+'locNoteType':None,
              ITSns+' '+'term':None,
              ITSns+' '+'termInfoRef':None,
              ITSns+' '+'translate':None,}
    __Test = {'system-bitrate':None,
              'system-captions':None,
              'system-language':None,
              'system-overdub-or-caption':None,
              'system-required':None,
              'system-screen-depth':None,
              'system-screen-size':None,
              'systemAudioDesc':None,
              'systemBaseProfile':None,
              'systemBitrate':None,
              'systemCaptions':None,
              'systemComponent':None,
              'systemCPU':None,
              'systemLanguage':None,
              'systemOperatingSystem':None,
              'systemOverdubOrSubtitle':None,
              'systemRequired':None,
              'systemScreenDepth':None,
              'systemScreenSize':None,
              'systemVersion':None,}
    __basicTiming = {'begin':None,
                     'dur':None,
                     'end':None,
                     'max':None,
                     'min':None,
                     'repeat':None,
                     'repeatCount':None,
                     'repeatDur':None,
                     }
    __Timing = {'fillDefault':None,
                'restart':None,
                'restartDefault':None,
                'syncBehavior':None,
                'syncBehaviorDefault':None,
                'syncMaster':None,
                'syncTolerance':None,
                'syncToleranceDefault':None,
                }
    __Timing.update(__basicTiming)
    __timeManipulations = {'speed':None,
                           'accelerate':None,
                           'decelerate':None,
                           'autoReverse':None,
                           }
    __MediaDescription = {'abstract':None,
                          'author':None,
                          'copyright':None,
                          }

    # all allowed elements with all their attributes
    _attributes = {
        'smil': {QTns+' ' 'time-slider':None,
                 QTns+' ' 'next':None,
                 QTns+' ' 'autoplay':None,
                 QTns+' ' 'chapter-mode':None,
                 QTns+' ' 'immediate-instantiation':None,
                 },
        'head': {},
        'body': {'accelerate':None,
                 'autoReverse':None,
                 'decelerate':None,
                 'fill':None,
                 'speed':None,
                 __layout:None,
                 GRiNSns+' ' 'hidden':None,
                 GRiNSns+' ' 'collapsed':None,
                 GRiNSns+' ' 'showtime':None,
                 GRiNSns+' ' 'timezoom':None,
                 GRiNSns+' ' 'comment':None,
                 GRiNSns+' ' 'thumbnailScale':None,
                 GRiNSns+' ' 'thumbnailIcon':None,
                 GRiNSns+' ' 'emptyIcon':None,
                 GRiNSns+' ' 'emptyText':None,
                 GRiNSns+' ' 'emptyColor':None,
                 GRiNSns+' ' 'emptyDur':None,
                 GRiNSns+' ' 'emptyShow':None,
                 GRiNSns+' ' 'nonEmptyIcon':None,
                 GRiNSns+' ' 'nonEmptyText':None,
                 GRiNSns+' ' 'nonEmptyColor':None,
                 GRiNSns+' ' 'dropIcon':None,
                 GRiNSns+' ' 'project_default_duration':None,
                 GRiNSns+' ' 'project_default_duration_image':None,
                 GRiNSns+' ' 'project_default_duration_text':None,
                 GRiNSns+' ' 'project_default_region_image':None,
                 GRiNSns+' ' 'project_default_region_video':None,
                 GRiNSns+' ' 'project_default_region_sound':None,
                 GRiNSns+' ' 'project_default_region_text':None,
                 GRiNSns+' ' 'project_forcechild':None,
                 },
        'meta': {'content':None,
                 'name':None,
                 'skip-content':None,
                 },
        'metadata': {'skip-content':None,
                     },
        __assets: {'skip-content':None,
                     },
        'layout': {'customTest':None,
                   'type':None,
                   },
        'root-layout': {'background-color':None,
                        'backgroundColor':None,
                        'backgroundImage':None,
                        'backgroundOpacity':None,
                        'backgroundRepeat':None,
                        'customTest':None,
                        'height':None,
                        'skip-content':None,
                        'width':None,
                        GRiNSns+' ' 'showEditBackground':None,
                        GRiNSns+' ' 'editBackground':None,
                        GRiNSns+' ' 'showEditBgMode':None,
                        GRiNSns+' ' 'traceImage':None,
                        GRiNSns+' ' 'collapsed':None,
                        GRiNSns+' ' 'previewShowOption':None,
                        RP9ns+' ' 'resizeBehavior':None,
                        },
        'topLayout': {'backgroundColor':None,
                      'backgroundImage':None,
                      'backgroundOpacity':None,
                      'backgroundRepeat':None,
                      'close':None,
                      'customTest':None,
                      'height':None,
                      'open':None,
                      'skip-content':None,
                      'width':None,
                      # edit preferences of new layout view
                      GRiNSns+' ' 'showEditBackground':None,
                      GRiNSns+' ' 'editBackground':None,
                      GRiNSns+' ' 'showEditBgMode':None,
                      GRiNSns+' ' 'traceImage':None,
                      GRiNSns+' ' 'collapsed':None,
                      GRiNSns+' ' 'previewShowOption':None,
                      RP9ns+' ' 'resizeBehavior':None,
                      },
        'region': {'background-color':None,
                   'backgroundColor':None,
                   'backgroundImage':None,
                   'backgroundOpacity':None,
                   'backgroundRepeat':None,
                   'bottom':None,
                   'chromaKey':None,
                   'chromaKeyOpacity':None,
                   'chromaKeyTolerance':None,
                   'customTest':None,
                   'erase':None,
                   'fit':None,
                   'height':None,
                   'left':None,
                   'mediaAlign':None,
                   'mediaBackgroundOpacity':None,
                   'mediaOpacity':None,
                   'panZoom':None,
                   'regAlign':None,
                   'regPoint':None,
                   'regionName':None,
                   'right':None,
                   'showBackground':None,
                   'skip-content':None,
                   'soundAlign':None,
                   'soundLevel':None,
                   'textAlign':None,
                   'textBackgroundColor':None,
                   'textColor':None,
                   'textDirection':None,
                   'textFontFamily':None,
                   'textFontSize':None,
                   'textFontStyle':None,
                   'textFontWeight':None,
                   'textMode':None,
                   'textPlace':None,
                   'textStyle':None,
                   'textWrapOption':None,
                   'textWritingMode':None,
                   'top':None,
                   'width':None,
                   'xml:space':None,
                   'z-index':None,
                   XHTMLns+' '+'role':None,
                   GRiNSns+' ' 'comment':None,
                   GRiNSns+' ' 'duration':None,
                   GRiNSns+' ' 'fgcolor':None,
                   GRiNSns+' ' 'file':None,
                   GRiNSns+' ' 'transparent':None,
                   GRiNSns+' ' 'type':None,
                   GRiNSns+' ' 'visible':None,
                   GRiNSns+' ' 'collapsed':None,
                   GRiNSns+' ' 'previewShowOption':None,
                   RP9ns+' ' 'opacity':None,
                   # edit preferences of new layout view
                   GRiNSns+' ' 'showEditBackground':None,
                   GRiNSns+' ' 'editBackground':None,
                   GRiNSns+' ' 'isDefault':None,
                },
        'regPoint': {'bottom':None,
                     'customTest':None,
                     'left':None,
                     'regAlign':None,
                     'right':None,
                     'skip-content':None,
                     'top':None,
                     },
        'paramGroup': {'skip-content':None,
                       },
        __layouts: {},
        __layout: {GRiNSns+' ' 'regions':None},
        __viewinfo: {
                        'view':None,
                        'top':None,
                        'left':None,
                        'width':None,
                        'height':None,
                        },
        'par': {'accelerate':None,
                'autoReverse':None,
                'customTest':None,
                'decelerate':None,
                'endsync':None,
                'expr':None,
                'fill':None,
                'region':None,
                'speed':None,
                XHTMLns+' '+'role':None,
                __layout:None,
                GRiNSns+' ' 'collapsed':None,
                GRiNSns+' ' 'showtime':None,
                GRiNSns+' ' 'timezoom':None,
                GRiNSns+' ' 'comment':None,
                GRiNSns+' ' 'thumbnailScale':None,
                GRiNSns+' ' 'thumbnailIcon':None,
                GRiNSns+' ' 'emptyIcon':None,
                GRiNSns+' ' 'emptyText':None,
                GRiNSns+' ' 'emptyColor':None,
                GRiNSns+' ' 'emptyDur':None,
                GRiNSns+' ' 'emptyShow':None,
                GRiNSns+' ' 'nonEmptyIcon':None,
                GRiNSns+' ' 'nonEmptyText':None,
                GRiNSns+' ' 'nonEmptyColor':None,
                GRiNSns+' ' 'dropIcon':None,
                GRiNSns+' ' 'project_default_duration':None,
                GRiNSns+' ' 'project_default_duration_image':None,
                GRiNSns+' ' 'project_default_duration_text':None,
                GRiNSns+' ' 'project_default_region_image':None,
                GRiNSns+' ' 'project_default_region_video':None,
                GRiNSns+' ' 'project_default_region_sound':None,
                GRiNSns+' ' 'project_default_region_text':None,
                GRiNSns+' ' 'project_forcechild':None,
                },
        'seq': {'accelerate':None,
                'autoReverse':None,
                'customTest':None,
                'decelerate':None,
                'expr':None,
                'fill':None,
                'region':None,
                'speed':None,
                XHTMLns+' '+'role':None,
                __layout:None,
                GRiNSns+' ' 'collapsed':None,
                GRiNSns+' ' 'showtime':None,
                GRiNSns+' ' 'timezoom':None,
                GRiNSns+' ' 'comment':None,
                GRiNSns+' ' 'thumbnailScale':None,
                GRiNSns+' ' 'thumbnailIcon':None,
                GRiNSns+' ' 'emptyIcon':None,
                GRiNSns+' ' 'emptyText':None,
                GRiNSns+' ' 'emptyColor':None,
                GRiNSns+' ' 'emptyDur':None,
                GRiNSns+' ' 'emptyShow':None,
                GRiNSns+' ' 'nonEmptyIcon':None,
                GRiNSns+' ' 'nonEmptyText':None,
                GRiNSns+' ' 'nonEmptyColor':None,
                GRiNSns+' ' 'dropIcon':None,
                GRiNSns+' ' 'project_default_region':None,
                GRiNSns+' ' 'project_default_type':None,
                GRiNSns+' ' 'project_bandwidth_fraction':None,
                GRiNSns+' ' 'project_readonly':None,
                GRiNSns+' ' 'project_default_duration':None,
                GRiNSns+' ' 'project_default_duration_image':None,
                GRiNSns+' ' 'project_default_duration_text':None,
                GRiNSns+' ' 'project_default_region_image':None,
                GRiNSns+' ' 'project_default_region_video':None,
                GRiNSns+' ' 'project_default_region_sound':None,
                GRiNSns+' ' 'project_default_region_text':None,
                GRiNSns+' ' 'project_forcechild':None,
                },
        'switch': {'allowReorder':None,
                   'customTest':None,
                   XHTMLns+' '+'role':None,
                   __layout:None,
                   GRiNSns+' ' 'project_default_duration':None,
                   GRiNSns+' ' 'project_default_duration_image':None,
                   GRiNSns+' ' 'project_default_duration_text':None,
                   GRiNSns+' ' 'thumbnailScale':None,
                   GRiNSns+' ' 'thumbnailIcon':None,
                   GRiNSns+' ' 'emptyIcon':None,
                   GRiNSns+' ' 'emptyText':None,
                   GRiNSns+' ' 'emptyColor':None,
                   GRiNSns+' ' 'emptyDur':None,
                   GRiNSns+' ' 'emptyShow':None,
                   GRiNSns+' ' 'nonEmptyIcon':None,
                   GRiNSns+' ' 'nonEmptyText':None,
                   GRiNSns+' ' 'nonEmptyColor':None,
                   GRiNSns+' ' 'dropIcon':None,
                   GRiNSns+' ' 'collapsed':None,
                   GRiNSns+' ' 'showtime':None,
                   GRiNSns+' ' 'timezoom':None,
                   },
        'excl': {'accelerate':None,
                 'autoReverse':None,
                 'customTest':None,
                 'decelerate':None,
                 'endsync':None,
                 'expr':None,
                 'fill':None,
                 'region':None,
                 'skip-content':None,
                 'speed':None,
                 XHTMLns+' '+'role':None,
                 __layout:None,
                 GRiNSns+' ' 'collapsed':None,
                 GRiNSns+' ' 'showtime':None,
                 GRiNSns+' ' 'timezoom':None,
                 GRiNSns+' ' 'comment':None,
                 GRiNSns+' ' 'thumbnailScale':None,
                 GRiNSns+' ' 'thumbnailIcon':None,
                 GRiNSns+' ' 'emptyIcon':None,
                 GRiNSns+' ' 'emptyText':None,
                 GRiNSns+' ' 'emptyColor':None,
                 GRiNSns+' ' 'emptyDur':None,
                 GRiNSns+' ' 'emptyShow':None,
                 GRiNSns+' ' 'nonEmptyIcon':None,
                 GRiNSns+' ' 'nonEmptyText':None,
                 GRiNSns+' ' 'nonEmptyColor':None,
                 GRiNSns+' ' 'dropIcon':None,
                 GRiNSns+' ' 'project_default_duration':None,
                 GRiNSns+' ' 'project_default_duration_image':None,
                 GRiNSns+' ' 'project_default_duration_text':None,
                 GRiNSns+' ' 'project_default_region_image':None,
                 GRiNSns+' ' 'project_default_region_video':None,
                 GRiNSns+' ' 'project_default_region_sound':None,
                 GRiNSns+' ' 'project_default_region_text':None,
                 GRiNSns+' ' 'project_forcechild':None,
                 },
        'priorityClass': {'customTest':None,
                          'higher':'pause',
                          'lower':'defer',
                          'pauseDisplay':None,
                          'peers':'stop',
                          'skip-content':None,
                          GRiNSns+' ' 'project_default_duration':None,
                          GRiNSns+' ' 'project_default_duration_image':None,
                          GRiNSns+' ' 'project_default_duration_text':None,
                          GRiNSns+' ' 'thumbnailScale':None,
                          GRiNSns+' ' 'thumbnailIcon':None,
                          GRiNSns+' ' 'emptyIcon':None,
                          GRiNSns+' ' 'emptyText':None,
                          GRiNSns+' ' 'emptyColor':None,
                          GRiNSns+' ' 'emptyDur':None,
                          GRiNSns+' ' 'emptyShow':None,
                          GRiNSns+' ' 'nonEmptyIcon':None,
                          GRiNSns+' ' 'nonEmptyText':None,
                          GRiNSns+' ' 'nonEmptyColor':None,
                          GRiNSns+' ' 'dropIcon':None,
                          GRiNSns+' ' 'collapsed':None,
                          GRiNSns+' ' 'showtime':None,
                          GRiNSns+' ' 'timezoom':None,
                          },
        'ref': {'accelerate':None,
                'autoReverse':None,
                'backgroundColor':None,
                'backgroundOpacity':None,
                'bottom':None,
                'chromaKey':None,
                'chromaKeyOpacity':None,
                'chromaKeyTolerance':None,
                'clip-begin':None,
                'clipBegin':None,
                'clip-end':None,
                'clipEnd':None,
                'customTest':None,
                'decelerate':None,
                'endsync':None,
                'erase':None,
                'expr':None,
                'fill':None,
                'fit':None,
                'height':None,
                'left':None,
                'mediaAlign':None,
                'mediaBackgroundOpacity':None,
                'mediaOpacity':None,
                'mediaRepeat':None,
                'panZoom':None,
                'paramGroup':None,
                'regAlign':None,
                'region':None,
                'regPoint':None,
                'right':None,
                'sensitivity':None,
                'speed':None,
                'soundAlign':None,
                'src':None,
                'tabindex':None,
                'top':None,
                'transIn':None,
                'transOut':None,
                'type':None,
                'width':None,
                'z-index':None,
                XHTMLns+' '+'role':None,
                __layout:None,
                GRiNSns+' ' 'bgcolor':None,
                GRiNSns+' ' 'collapsed':None,
                GRiNSns+' ' 'comment':None,
                GRiNSns+' ' 'captionchannel':None,
                GRiNSns+' ' 'thumbnailScale':None,
                GRiNSns+' ' 'thumbnailIcon':None,
                GRiNSns+' ' 'project_audiotype':None,
                GRiNSns+' ' 'project_convert':None,
                GRiNSns+' ' 'project_mobile':None,
                GRiNSns+' ' 'project_perfect':None,
                GRiNSns+' ' 'project_quality':None,
                GRiNSns+' ' 'project_targets':None,
                GRiNSns+' ' 'project_videotype':None,
                GRiNSns+' ' 'showAnimationPath':None,
                GRiNSns+' ' 'showtime':None,
                GRiNSns+' ' 'timezoom':None,
                GRiNSns+' ' 'allowedmimetypes':None,
                GRiNSns+' ' 'iheight':None,
                GRiNSns+' ' 'iwidth':None,
                GRiNSns+' ' 'idur':None,
                GRiNSns+' ' 'previewShowOption':None,
                QTns+' ' 'immediate-instantiation':None,
                QTns+' ' 'bitrate':None,
                QTns+' ' 'system-mime-type-supported':None,
                QTns+' ' 'attach-timebase':None,
                QTns+' ' 'chapter':None,
                QTns+' ' 'composite-mode':None,
                RP9ns+' ' 'backgroundOpacity':None,
                RP9ns+' ' 'chromaKey':None,
                RP9ns+' ' 'chromaKeyOpacity':None,
                RP9ns+' ' 'chromaKeyTolerance':None,
                RP9ns+' ' 'mediaOpacity':None,
                },
        'brush': {'accelerate':None,
                  'autoReverse':None,
                  'backgroundColor':None,
                  'backgroundOpacity':None,
                  'bottom':None,
                  'color':None,
                  'customTest':None,
                  'decelerate':None,
                  'endsync':None,
                  'erase':None,
                  'expr':None,
                  'fill':None,
                  'fit':None,
                  'height':None,
                  'left':None,
                  'mediaAlign':None,
                  'paramGroup':None,
                  'regAlign':None,
                  'region':None,
                  'regPoint':None,
                  'right':None,
                  'sensitivity':None,
                  'skip-content':None,
                  'speed':None,
                  'tabindex':None,
                  'top':None,
                  'transIn':None,
                  'transOut':None,
                  'width':None,
                  'z-index':None,
                  XHTMLns+' '+'role':None,
                  __layout:None,
                  GRiNSns+' ' 'collapsed':None,
                  GRiNSns+' ' 'thumbnailScale':None,
                  GRiNSns+' ' 'thumbnailIcon':None,
                  GRiNSns+' ' 'bgcolor':None,
                  GRiNSns+' ' 'comment':None,
                  GRiNSns+' ' 'showtime':None,
                  GRiNSns+' ' 'showAnimationPath':None,
                  GRiNSns+' ' 'timezoom':None,
                  GRiNSns+' ' 'previewShowOption':None,
                  QTns+' ' 'immediate-instantiation':None,
                  QTns+' ' 'bitrate':None,
                  QTns+' ' 'system-mime-type-supported':None,
                  QTns+' ' 'attach-timebase':None,
                  QTns+' ' 'chapter':None,
                  QTns+' ' 'composite-mode':None,
                  },
        'param': {'customTest':None,
                  'name':None,
                  'skip-content':None,
                  'type':None,
                  'value':None,
                  'valuetype':None,
                  },
        'a': {'accesskey':None,
              'actuate':None,
              'customTest':None,
              'destinationLevel':None,
              'destinationPlaystate':None,
              'external':None,
              'href':None,
              'show':None,
              'sourceLevel':None,
              'sourcePlaystate':None,
              'tabindex':None,
              'target':None,
              XHTMLns+' '+'role':None,
              },
        'area': {'accesskey':None,
                 'actuate':None,
                 'coords':None,
                 'customTest':None,
                 'destinationLevel':None,
                 'destinationPlaystate':None,
                 'expr':None,
                 'external':None,
                 'fragment':None,
                 'href':None,
                 'nohref':None,
                 'shape':None,
                 'show':None,
                 'skip-content':None,
                 'sourceLevel':None,
                 'sourcePlaystate':None,
                 'tabindex':None,
                 'target':None,
                 RP9ns+' ' 'sendTo':None,
                 XHTMLns+' '+'role':None,
                 },
        'customAttributes': {'skip-content':None,
                             },
        'customTest': {'defaultState':None,
                       'override':None,
                       'skip-content':None,
                       'uid':None,
                       },
        'transition':{'borderColor':None,
                      'borderWidth':None,
                      'customTest':None,
                      'direction':None,
                      'dur':None,
                      'endProgress':None,
                      'fadeColor':None,
                      'horzRepeat':None,
                      'scope':None,
                      'skip-content':None,
                      'startProgress':None,
                      'subtype':None,
                      'type':None,
                      'vertRepeat':None,
                      },
        'transitionFilter':{'borderColor':None,
                            'borderWidth':None,
                            'by':None,
                            'calcMode':None,
                            'fadeColor':None,
                            'from':None,
                            'horzRepeat':None,
                            'mode':None,
                            'subtype':None,
                            'targetElement':None,
                            'to':None,
                            'type':None,
                            'values':None,
                            'vertRepeat':None,
                            },
        'prefetch': {'accelerate':None,
                     'autoReverse':None,
                     'bandwidth':None,
                     'clip-begin':None,
                     'clip-end':None,
                     'clipBegin':None,
                     'clipEnd':None,
                     'customTest':None,
                     'decelerate':None,
                     'expr':None,
                     'mediaSize':None,
                     'mediaTime':None,
                     'skip-content':None,
                     'speed':None,
                     'src':None,
                     GRiNSns+' ' 'showtime':None,
                     GRiNSns+' ' 'timezoom':None,
                     },
        'animate': {'accelerate':None,
                    'accumulate':None,
                    'additive':None,
                    'attributeName':None,
                    'attributeType':None,
                    'autoReverse':None,
                    'by':None,
                    'calcMode':None,
                    'customTest':None,
                    'decelerate':None,
                    'fill':None,
                    'from':None,
                    'keySplines':None,
                    'keyTimes':None,
                    'skip-content':None,
                    'speed':None,
                    'targetElement':None,
                    'to':None,
                    'values':None,
                    GRiNSns+' ' 'editGroup':None,
                    },
        'animateColor': {'accelerate':None,
                         'accumulate':None,
                         'additive':None,
                         'attributeName':None,
                         'attributeType':None,
                         'autoReverse':None,
                         'by':None,
                         'calcMode':None,
                         'customTest':None,
                         'decelerate':None,
                         'expr':None,
                         'fill':None,
                         'from':None,
                         'keySplines':None,
                         'keyTimes':None,
                         'skip-content':None,
                         'speed':None,
                         'targetElement':None,
                         'to':None,
                         'values':None,
                         },
        'animateMotion': {'accelerate':None,
                          'accumulate':None,
                          'additive':None,
                          'autoReverse':None,
                          'by':None,
                          'calcMode':None,
                          'customTest':None,
                          'decelerate':None,
                          'expr':None,
                          'fill':None,
                          'from':None,
                          'keySplines':None,
                          'keyTimes':None,
                          'origin':None,
                          'path':None,
                          'skip-content':None,
                          'speed':None,
                          'targetElement':None,
                          'to':None,
                          'values':None,
                          GRiNSns+' ' 'editGroup':None,
                          },
        'set': {'accelerate':None,
                'attributeName':None,
                'attributeType':None,
                'autoReverse':None,
                'customTest':None,
                'decelerate':None,
                'expr':None,
                'fill':None,
                'skip-content':None,
                'speed':None,
                'targetElement':None,
                'to':None,
                },
        'smilText': {'accelerate':None,
                     'autoReverse':None,
                     'backgroundColor':None,
                     'backgroundOpacity':None,
                     'bottom':None,
                     'chromaKey':None,
                     'chromaKeyOpacity':None,
                     'chromaKeyTolerance':None,
                     'customTest':None,
                     'decelerate':None,
                     'endsync':None,
                     'erase':None,
                     'expr':None,
                     'fill':None,
                     'fit':None,
                     'height':None,
                     'left':None,
                     'mediaAlign':None,
                     'mediaBackgroundOpacity':None,
                     'mediaOpacity':None,
                     'paramGroup':None,
                     'regAlign':None,
                     'region':None,
                     'regPoint':None,
                     'right':None,
                     'sensitivity':None,
                     'skip-content':None,
                     'speed':None,
                     'tabindex':None,
                     'textAlign':None,
                     'textBackgroundColor':None,
                     'textColor':None,
                     'textConceal':None,
                     'textFontFamily':None,
                     'textFontSize':None,
                     'textFontStyle':None,
                     'textFontWeight':None,
                     'textMode':None,
                     'textPlace':None,
                     'textRate':None,
                     'textStyle':None,
                     'textWrapOption':None,
                     'textWritingMode':None,
                     'top':None,
                     'transIn':None,
                     'transOut':None,
                     'width':None,
                     'xml:space':None,
                     'z-index':None,
                     XHTMLns+' '+'role':None,
                     },
        'textStyle': {'textAlign':None,
                      'textBackgroundColor':None,
                      'textColor':None,
                      'textConceal':None,
                      'textDirection':None,
                      'textFontFamily':None,
                      'textFontSize':None,
                      'textFontStyle':None,
                      'textFontWeight':None,
                      'textMode':None,
                      'textPlace':None,
                      'textRate':None,
                      'textStyle':None,
                      'textWrapOption':None,
                      'textWritingMode':None,
                      'xml:space':None,
                      },
        'textStyling': {},
        'br': {},
        'clear': {'begin':None,
                  'next':None,
                  },
        'tev': {'begin':None,
                'next':None,
                },
        'div': {'textAlign':None,
                'textBackgroundColor':None,
                'textColor':None,
                'textFontFamily':None,
                'textFontSize':None,
                'textFontStyle':None,
                'textFontWeight':None,
                'textStyle':None,
                'textWrapOption':None,
                'textWritingMode':None,
                'xml:space':None,
        },
        'span': {'textBackgroundColor':None,
                 'textColor':None,
                 'textDirection':None,
                 'textFontFamily':None,
                 'textFontSize':None,
                 'textFontStyle':None,
                 'textFontWeight':None,
                 'textStyle':None,
                 'textWrapOption':None,
                 'xml:space':None,
        },
        'p': {'textBackgroundColor':None,
              'textColor':None,
              'textFontFamily':None,
              'textFontSize':None,
              'textFontStyle':None,
              'textFontWeight':None,
              'textStyle':None,
              'textWrapOption':None,
              'textWritingMode':None,
              'xml:space':None,
              },
        'state': {'language':None,
                  'skip-content':None,
                  'src':None,
                  },
        'delvalue': {'accelerate':None,
                     'autoReverse':None,
                     'customTest':None,
                     'decelerate':None,
                     'expr':None,
                     'ref':None,
                     'skip-content':None,
                     'speed':None,
                     },
        'newvalue': {'accelerate':None,
                     'autoReverse':None,
                     'customTest':None,
                     'decelerate':None,
                     'expr':None,
                     'name':None,
                     'ref':None,
                     'skip-content':None,
                     'speed':None,
                     'value':None,
                     'where':None,
                     },
        'setvalue': {'accelerate':None,
                     'autoReverse':None,
                     'customTest':None,
                     'decelerate':None,
                     'expr':None,
                     'ref':None,
                     'skip-content':None,
                     'speed':None,
                     'value':None,
                     },
        'send': {'accelerate':None,
                 'autoReverse':None,
                 'customTest':None,
                 'decelerate':None,
                 'expr':None,
                 'skip-content':None,
                 'speed':None,
                 'submission':None,
                 },
        'submission': {'action':None,
                       'method':None,
                       'ref':None,
                       'replace':None,
                       'target':None,
                       }
        }

    _attributes['anchor'] = _attributes['area'].copy()

    # Abbreviations for collections of elements
    __media_object = ['audio', 'video', 'text', 'img', 'animation',
                      'textstream', 'ref', 'brush',
                      'prefetch', 'smilText',
                      'send', 'setvalue', 'newvalue', 'delvalue']
    __schedule = ['par', 'seq', 'excl'] + __media_object
    __animate_elements = ['animate', 'animateMotion', 'animateColor', 'set', 'transitionFilter']
    __metadata = ['metadata']
    __container_content = __schedule + __animate_elements + __metadata + ['switch', 'a', __assets]
    __media_content = ['anchor', 'area', 'param', 'switch'] + __animate_elements + __metadata

    # all media objects are like ref
    __at = None
    for __el in __media_object:
        if not _attributes.has_key(__el):
            _attributes[__el] = _attributes['ref']

    # add TimeManipulations to certain elements
    for __el in __animate_elements:
        _attributes[__el].update(__timeManipulations)

    # Core, Test and I18n attribs are added to all elements in the language
    for __el in _attributes.keys():
        _attributes[__el].update(__Core)
        if __el not in ('body', 'br', 'clear', 'customAttributes',
                        'customTest', 'div', 'head', 'meta', 'metadata',
                        'p', 'paramGroup', 'span', 'state', 'submission',
                        'tev', 'textStyling', 'transitionFilter'):
            _attributes[__el].update(__Test)
        _attributes[__el].update(__I18n)

    # add basicTiming to certain elements
    for __el in ('a', 'area', 'anchor', 'transitionFilter'):
        _attributes[__el].update(__basicTiming)

    # add Timing to certain other elements
    for __el in ('animate', 'animateColor', 'animateMotion', 'animation',
                 'audio', 'body', 'brush', 'delvalue', 'excl', 'img',
                 'newvalue', 'par', 'prefetch', 'ref', 'send', 'seq',
                 'set', 'setvalue', 'smilText', 'text', 'textstream', 'video'):
        if __el[:len(GRiNSns)+1] == GRiNSns+' ':
            for __key, __val in __Timing.items():
                if ' ' in __key:
                    _attributes[__el][__key] = __val
                    _attributes[__el][GRiNSns+' '+__key.split(' ')[1]] = __val
                else:
                    _attributes[__el][GRiNSns+' '+__key] = __val
        else:
            _attributes[__el].update(__Timing)

    # add MediaDescription to certain elements
    for __el in ('animation', 'audio', 'body', 'brush', 'div',
                 'excl', 'img', 'p', 'par', 'prefetch', 'ref',
                 'seq', 'smilText', 'span', 'text', 'textstream', 'video'):
        _attributes[__el].update(__MediaDescription)

    # all entities with their allowed content
    # no allowed content is default, so we don't specify empty ones here
    entities = {
        'a': __schedule + __animate_elements + __metadata + ['switch'],
        'anchor': __metadata + ['animate', 'set'],
        'animate': __metadata,
        'animateColor': __metadata,
        'animateMotion': __metadata,
        'animation': __media_content,
        'area': __metadata + ['animate', 'set'],
        'audio': __media_content,
        'body': __container_content,
        'br': __metadata,
        'brush': __media_content,
        'clear': __metadata,
        'customAttributes': ['customTest'] + __metadata,
        'customTest': __metadata,
        'delvalue': __metadata,
        'div': ['tev', 'clear', 'br', 'div', 'p', 'span'] + __metadata,
        'excl': __container_content + ['priorityClass'],
        'head': ['layout', 'switch', 'meta', 'metadata', 'customAttributes', __layouts, 'state', 'submission', 'transition', __viewinfo, 'paramGroup'],
        'img': __media_content,
        'layout': ['region', 'root-layout', 'topLayout', 'regPoint'] + __metadata,
        'newvalue': __metadata,
        'p': ['tev', 'clear', 'br', 'span'] + __metadata,
        'par': __container_content,
        'param': __metadata,
        'paramGroup': ['param'] + __metadata,
        'priorityClass': __container_content,
        'ref': __media_content,
        'region': ['region'] + __metadata,
        'regPoint': __metadata,
        'root-layout': __metadata,
        'send': __metadata,
        'seq': __container_content,
        'set': __metadata,
        'smil': ['head', 'body'] + __metadata,
        'smilText': ['tev', 'clear', 'br', 'span', 'p', 'div'] + __metadata,
        'span': ['tev', 'clear', 'br', 'span'] + __metadata,
        'submission': __metadata,
        'switch': ['layout'] + __container_content,
        'tev': __metadata,
        'text': __media_content,
        'textstream': __media_content,
        'topLayout': ['region'] + __metadata,
        'transition': __metadata,
        'video': __media_content,
        __layouts: [__layout],
        __assets: __container_content,

## when used, this should be moved outside of this dict
##     __Schedule = ['par', 'seq', 'excl']
##     __MediaContent = ['text', 'img', 'audio', 'video', 'ref', 'animation', 'textstream', 'brush', 'param']
##     __ContentControl = ['switch', 'prefetch']
##     __LinkAnchor = ['a', 'area', 'anchor']
##     __Animation = ['animate', 'set', 'animateMotion', 'animateColor', 'transitionFilter']

##         'switch': __Schedule + __MediaContent + __ContentControl + __LinkAnchor + __Animation + ['priorityClass','layout'],
##         'customAttributes': ['customTest'],
##         'region': ['region'],
##         'topLayout': ['region'],
##         'layout': ['root-layout', 'region', 'topLayout', 'regPoint'],
##         'a': __Schedule + __MediaContent + __ContentControl + __Animation,
##         'area': ['animate', 'set'],
##         'anchor': ['animate', 'set'],
##         'text': ['param', 'area', 'anchor', 'switch'] + __Animation,
##         'img': ['param', 'area', 'anchor', 'switch'] + __Animation,
##         'audio': ['param', 'area', 'anchor', 'switch'] + __Animation,
##         'animation': ['param', 'area', 'anchor', 'switch'] + __Animation,
##         'video': ['param', 'area', 'anchor', 'switch'] + __Animation,
##         'ref': ['param', 'area', 'anchor', 'switch'] + __Animation,
##         'textstream': ['param', 'area', 'anchor', 'switch'] + __Animation,
##         'brush': ['param', 'area', 'anchor', 'switch'] + __Animation,
##         'smil': ['head', 'body'],
##         'head': ['meta', 'customAttributes', 'metadata', 'layout', 'switch', 'transition'],
##         'body': __Schedule + __MediaContent + __ContentControl + ['a'],
##         'par': __Schedule + __MediaContent + __ContentControl + ['a'] + __Animation,
##         'seq': __Schedule + __MediaContent + __ContentControl + ['a'] + __Animation,
##         'excl': __Schedule + __MediaContent + __ContentControl + ['a'] + __Animation + ['priorityClass'],
##         'priorityClass': __Schedule + __MediaContent + __ContentControl + ['a'] + __Animation,
            }

    # cleanup
    __el = __atd = __at = __vl = __key = __val = __ns = __sns = None
    del __el, __atd, __at, __vl, __key, __val, __ns, __sns
    del __media_object, __schedule, __container_content,
    del __media_content
    del __layouts, __layout
    del __animate_elements
    del __I18n, __basicTiming, __Timing, __Core, __Test
