/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grins_GRiNSPlayer */

#ifndef _Included_grins_GRiNSPlayer
#define _Included_grins_GRiNSPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     grins_GRiNSPlayer
 * Method:    initializeThreadContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_initializeThreadContext
  (JNIEnv *, jobject);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    uninitializeThreadContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_uninitializeThreadContext
  (JNIEnv *, jobject);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_nconnect
  (JNIEnv *, jobject);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ndisconnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_ndisconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetPermission
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_ngetPermission
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nopen
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nopen
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nclose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nclose
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nplay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nplay
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nstop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nstop
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    npause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_npause
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nupdate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nupdate
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_ngetState
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetTopLayoutCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_ngetTopLayoutCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nsetTopLayoutWindow
 * Signature: (IILjava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nsetTopLayoutWindow
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetTopLayoutDimensions
 * Signature: (II)Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_grins_GRiNSPlayer_ngetTopLayoutDimensions
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetTopLayoutTitle
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_grins_GRiNSPlayer_ngetTopLayoutTitle
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetTopLayoutState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_ngetTopLayoutState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nmouseClicked
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nmouseClicked
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nmouseMoved
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_grins_GRiNSPlayer_nmouseMoved
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetDuration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_grins_GRiNSPlayer_ngetDuration
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nsetTime
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nsetTime
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetTime
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_grins_GRiNSPlayer_ngetTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nsetSpeed
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nsetSpeed
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetSpeed
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_grins_GRiNSPlayer_ngetSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetCookie
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_ngetCookie
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetFrameRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_ngetFrameRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetMediaFrameRate
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_ngetMediaFrameRate
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
