/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GRiNSCanvas */

#ifndef _Included_GRiNSCanvas
#define _Included_GRiNSCanvas
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
#undef GRiNSCanvas_assert
#define GRiNSCanvas_assert 0L
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef GRiNSCanvas_TOP_ALIGNMENT
#define GRiNSCanvas_TOP_ALIGNMENT 0.0f
#undef GRiNSCanvas_CENTER_ALIGNMENT
#define GRiNSCanvas_CENTER_ALIGNMENT 0.5f
#undef GRiNSCanvas_BOTTOM_ALIGNMENT
#define GRiNSCanvas_BOTTOM_ALIGNMENT 1.0f
#undef GRiNSCanvas_LEFT_ALIGNMENT
#define GRiNSCanvas_LEFT_ALIGNMENT 0.0f
#undef GRiNSCanvas_RIGHT_ALIGNMENT
#define GRiNSCanvas_RIGHT_ALIGNMENT 1.0f
#undef GRiNSCanvas_serialVersionUID
#define GRiNSCanvas_serialVersionUID -7644114512714619750LL
/* Inaccessible static: nameCounter */
#undef GRiNSCanvas_serialVersionUID
#define GRiNSCanvas_serialVersionUID -2284879212465893870LL
/*
 * Class:     GRiNSCanvas
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GRiNSCanvas_close
  (JNIEnv *, jobject);

/*
 * Class:     GRiNSCanvas
 * Method:    connect
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_GRiNSCanvas_connect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     GRiNSCanvas
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GRiNSCanvas_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     GRiNSCanvas
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GRiNSCanvas_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     GRiNSCanvas
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_GRiNSCanvas_paint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     GRiNSCanvas
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GRiNSCanvas_pause
  (JNIEnv *, jobject);

/*
 * Class:     GRiNSCanvas
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GRiNSCanvas_play
  (JNIEnv *, jobject);

/*
 * Class:     GRiNSCanvas
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GRiNSCanvas_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
