/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GRiNSViewport */

#ifndef _Included_GRiNSViewport
#define _Included_GRiNSViewport
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
#undef GRiNSViewport_assert
#define GRiNSViewport_assert 0L
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef GRiNSViewport_TOP_ALIGNMENT
#define GRiNSViewport_TOP_ALIGNMENT 0.0f
#undef GRiNSViewport_CENTER_ALIGNMENT
#define GRiNSViewport_CENTER_ALIGNMENT 0.5f
#undef GRiNSViewport_BOTTOM_ALIGNMENT
#define GRiNSViewport_BOTTOM_ALIGNMENT 1.0f
#undef GRiNSViewport_LEFT_ALIGNMENT
#define GRiNSViewport_LEFT_ALIGNMENT 0.0f
#undef GRiNSViewport_RIGHT_ALIGNMENT
#define GRiNSViewport_RIGHT_ALIGNMENT 1.0f
#undef GRiNSViewport_serialVersionUID
#define GRiNSViewport_serialVersionUID -7644114512714619750LL
/* Inaccessible static: nameCounter */
#undef GRiNSViewport_serialVersionUID
#define GRiNSViewport_serialVersionUID -2284879212465893870LL
/*
 * Class:     GRiNSViewport
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSViewport_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSViewport
 * Method:    connect
 * Signature: (Ljava/awt/Graphics;)I
 */
JNIEXPORT jint JNICALL Java_GRiNSViewport_connect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     GRiNSViewport
 * Method:    disconnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSViewport_disconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSViewport
 * Method:    getSizeAdvice
 * Signature: (I)Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_GRiNSViewport_getSizeAdvice
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSViewport
 * Method:    open
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GRiNSViewport_open
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     GRiNSViewport
 * Method:    pause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSViewport_pause
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSViewport
 * Method:    play
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSViewport_play
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSViewport
 * Method:    stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSViewport_stop
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSViewport
 * Method:    update
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSViewport_update
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
