/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grins_GRiNSPlayerMonitor */

#ifndef _Included_grins_GRiNSPlayerMonitor
#define _Included_grins_GRiNSPlayerMonitor
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: threadInitNumber */
/* Inaccessible static: stopThreadPermission */
#undef grins_GRiNSPlayerMonitor_MIN_PRIORITY
#define grins_GRiNSPlayerMonitor_MIN_PRIORITY 1L
#undef grins_GRiNSPlayerMonitor_NORM_PRIORITY
#define grins_GRiNSPlayerMonitor_NORM_PRIORITY 5L
#undef grins_GRiNSPlayerMonitor_MAX_PRIORITY
#define grins_GRiNSPlayerMonitor_MAX_PRIORITY 10L
/*
 * Class:     grins_GRiNSPlayerMonitor
 * Method:    initializeThreadContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayerMonitor_initializeThreadContext
  (JNIEnv *, jobject);

/*
 * Class:     grins_GRiNSPlayerMonitor
 * Method:    uninitializeThreadContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayerMonitor_uninitializeThreadContext
  (JNIEnv *, jobject);

/*
 * Class:     grins_GRiNSPlayerMonitor
 * Method:    nconnect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayerMonitor_nconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayerMonitor
 * Method:    ndisconnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayerMonitor_ndisconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayerMonitor
 * Method:    ngetState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayerMonitor_ngetState
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayerMonitor
 * Method:    ngetTime
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_grins_GRiNSPlayerMonitor_ngetTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayerMonitor
 * Method:    ngetTopLayoutCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayerMonitor_ngetTopLayoutCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayerMonitor
 * Method:    ngetTopLayoutState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayerMonitor_ngetTopLayoutState
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
