/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GRiNSPlayer */

#ifndef _Included_GRiNSPlayer
#define _Included_GRiNSPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GRiNSPlayer
 * Method:    nclose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSPlayer_nclose
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSPlayer
 * Method:    nconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GRiNSPlayer_nconnect__
  (JNIEnv *, jobject);

/*
 * Class:     GRiNSPlayer
 * Method:    nconnect
 * Signature: (Ljava/awt/Component;)I
 */
JNIEXPORT jint JNICALL Java_GRiNSPlayer_nconnect__Ljava_awt_Component_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     GRiNSPlayer
 * Method:    ndisconnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSPlayer_ndisconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSPlayer
 * Method:    ngetDuration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_GRiNSPlayer_ngetDuration
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSPlayer
 * Method:    ngetPreferredSize
 * Signature: (I)Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_GRiNSPlayer_ngetPreferredSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSPlayer
 * Method:    ngetSpeed
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_GRiNSPlayer_ngetSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSPlayer
 * Method:    ngetState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_GRiNSPlayer_ngetState
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSPlayer
 * Method:    ngetTime
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_GRiNSPlayer_ngetTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSPlayer
 * Method:    nopen
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GRiNSPlayer_nopen
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     GRiNSPlayer
 * Method:    npause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSPlayer_npause
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSPlayer
 * Method:    nplay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSPlayer_nplay
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSPlayer
 * Method:    nsetSpeed
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_GRiNSPlayer_nsetSpeed
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     GRiNSPlayer
 * Method:    nsetTime
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_GRiNSPlayer_nsetTime
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     GRiNSPlayer
 * Method:    nstop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSPlayer_nstop
  (JNIEnv *, jobject, jint);

/*
 * Class:     GRiNSPlayer
 * Method:    nupdate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_GRiNSPlayer_nupdate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
