/*
	A basic extension of the java.applet.Applet class
 */

import java.awt.*;
import java.awt.event.*;
import java.applet.*;


public class GRiNSApplet extends Applet
{
	public void init()
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setSize(350,350);
		add(grinsCanvas);
		grinsCanvas.setBackground(java.awt.Color.pink);
		grinsCanvas.setBounds(25,25,300,300);
		//}}
	}
	
	//{{DECLARE_CONTROLS
	GRiNSCanvas grinsCanvas = new GRiNSCanvas();
	//}}
	
	// standalone execution support
    public static void main(String args[]) 
		{
		Frame f = new Frame("GRiNS Player");
		f.addWindowListener(
			new WindowAdapter() 
				{ 
				public void windowClosing(WindowEvent e) 
					{System.exit(0);} 
				});
	
		GRiNSApplet	appletTemplate = new GRiNSApplet();

		appletTemplate.init();
		appletTemplate.start();

		f.add("Center", appletTemplate);
		f.setSize(360, 380);
		f.show();
		}
	
}
