/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class grins_GRiNSPlayer */

#ifndef _Included_grins_GRiNSPlayer
#define _Included_grins_GRiNSPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     grins_GRiNSPlayer
 * Method:    initializeThreadContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_initializeThreadContext
  (JNIEnv *, jobject);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nclose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nclose
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_nconnect
  (JNIEnv *, jobject);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ndisconnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_ndisconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetCookie
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_ngetCookie
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetDuration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_grins_GRiNSPlayer_ngetDuration
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetPreferredSize
 * Signature: (I)Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_grins_GRiNSPlayer_ngetPreferredSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetSpeed
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_grins_GRiNSPlayer_ngetSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_grins_GRiNSPlayer_ngetState
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    ngetTime
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_grins_GRiNSPlayer_ngetTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nmouseClicked
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nmouseClicked
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nmouseMoved
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_grins_GRiNSPlayer_nmouseMoved
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nopen
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nopen
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    npause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_npause
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nplay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nplay
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nsetSpeed
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nsetSpeed
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nsetTime
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nsetTime
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nsetWindow
 * Signature: (ILjava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nsetWindow
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nstop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nstop
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    nupdate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_nupdate
  (JNIEnv *, jobject, jint);

/*
 * Class:     grins_GRiNSPlayer
 * Method:    uninitializeThreadContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_grins_GRiNSPlayer_uninitializeThreadContext
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
