__version__ = "$Id$"

languages = (
        ('af', 'Afrikaans'),
        ('sq', 'Albanian'),
        ('ar-iq', 'Arabic (Iraq)'),
        ('ar-dz', 'Arabic (Algeria)'),
        ('ar-bh', 'Arabic (Bahrain)'),
        ('ar-eg', 'Arabic (Egypt)'),
        ('ar-jo', 'Arabic (Jordan)'),
        ('ar-kw', 'Arabic (Kuwait)'),
        ('ar-lb', 'Arabic (Lebanon)'),
        ('ar-ly', 'Arabic (Libya)'),
        ('ar-ma', 'Arabic (Morocco)'),
        ('ar-om', 'Arabic (Oman)'),
        ('ar-qa', 'Arabic (Qatar)'),
        ('ar-sa', 'Arabic (Saudi Arabia)'),
        ('ar-sy', 'Arabic (Syria)'),
        ('ar-tn', 'Arabic (Tunisia)'),
        ('ar-ae', 'Arabic (U.A.E.)'),
        ('ar-ye', 'Arabic (Yemen)'),
        ('eu', 'Basque'),
        ('bg', 'Bulgarian'),
        ('ca', 'Catalan'),
        ('zh-hk', 'Chinese (Hong Kong)'),
        ('zh-cn', 'Chinese (People\'s Republic)'),
        ('zh-sg', 'Chinese (Singapore)'),
        ('zh-tw', 'Chinese (Taiwan)'),
        ('hr', 'Croatian'),
        ('cs', 'Czech'),
        ('da', 'Danish'),
        ('nl', 'Dutch (Standard)'),
        ('nl-be', 'Dutch (Belgian)'),
        ('en', 'English'),
        ('en-au', 'English (Australian)'),
        ('en-bz', 'English (Belize)'),
        ('en-gb', 'English (British)'),
        ('en-ca', 'English (Canadian)'),
        ('en-cn', 'English (Caribbean)'),
        ('en-ie', 'English (Ireland)'),
        ('en-jm', 'English (Jamaica)'),
        ('en-nz', 'English (New Zealand)'),
        ('en-za', 'English (South Africa)'),
        ('en-tt', 'English (Trinidad)'),
        ('en-us', 'English (United States)'),
        ('et', 'Estonian'),
        ('fo', 'Faeroese'),
        ('fi', 'Finnish'),
        ('fr-be', 'French (Belgian)'),
        ('fr-ca', 'French (Canadian)'),
        ('fr-lu', 'French (Luxembourg)'),
        ('fr', 'French (Standard)'),
        ('fr-ch', 'French (Swiss)'),
        ('de-at', 'German (Austrian)'),
        ('de-li', 'German (Liechtenstein)'),
        ('de-lu', 'German (Luxembourg)'),
        ('de', 'German (Standard)'),
        ('de-ch', 'German (Swiss)'),
        ('el', 'Greek'),
        ('he', 'Hebrew'),
        ('hu', 'Hungarian'),
        ('is', 'Icelandic'),
        ('id', 'Indonesian'),
        ('iu', 'Inuktitut'),
        ('it', 'Italian (Standard)'),
        ('it-ch', 'Italian (Swiss)'),
        ('ja', 'Japanese'),
        ('ko', 'Korean'),
        ('ko-jb', 'Korean (Johab)'),
        ('lv', 'Latvian'),
        ('lt', 'Lithuanian'),
        ('no', 'Norwegian'),
        ('pl', 'Polish'),
        ('pt-br', 'Portuguese (Brazilian)'),
        ('pt', 'Portuguese (Standard)'),
        ('ro', 'Romanian'),
        ('sr', 'Serbian'),
        ('sk', 'Slovak'),
        ('sl', 'Slovenian'),
        ('es-ar', 'Spanish (Argentina)'),
        ('es-bo', 'Spanish (Bolivia)'),
        ('es-cl', 'Spanish (Chile)'),
        ('es-co', 'Spanish (Colombia)'),
        ('es-cr', 'Spanish (Costa Rica)'),
        ('es-do', 'Spanish (Dominican Republic)'),
        ('es-ec', 'Spanish (Ecuador)'),
        ('es-sv', 'Spanish (El Salvador)'),
        ('es-gt', 'Spanish (Guatemala)'),
        ('es-hn', 'Spanish (Honduras)'),
        ('es-mx', 'Spanish (Mexican)'),
        ('es-ni', 'Spanish (Nicaragua)'),
        ('es-pa', 'Spanish (Panama)'),
        ('es-py', 'Spanish (Paraguay)'),
        ('es-pe', 'Spanish (Peru)'),
        ('es-pr', 'Spanish (Puerto Rico)'),
        ('es', 'Spanish (Spain)'),
        ('es-uy', 'Spanish (Uruguay)'),
        ('es-ve', 'Spanish (Venezuela)'),
        ('sv', 'Swedish'),
        ('sv-fi', 'Swedish (Finland)'),
        ('th', 'Thai'),
        ('tr', 'Turkish'),
        ('ug', 'Uigur'),
        ('uk', 'Ukrainian'),
        ('vi', 'Vietnamese'),
        ('yi', 'Yiddish'),
        ('za' ,'Zhuang'),
        )

a2l = {}
l2a = {}
for _a, _l in languages:
    a2l[_a] = _l
    l2a[_l] = _a
