# Color assignments (RGB)
import settings;

BGCOLOR = settings.get('structure_bgcolor')
LEAFCOLOR = settings.get('structure_leafcolor')
RPCOLOR = settings.get('structure_rpcolor')
SLIDECOLOR = settings.get('structure_slidecolor')
BAGCOLOR = settings.get('structure_bagcolor')
ALTCOLOR = settings.get('structure_altcolor')
PARCOLOR = settings.get('structure_parcolor')
SEQCOLOR = settings.get('structure_seqcolor')
EXCLCOLOR = settings.get('structure_exclcolor')
PRIOCOLOR = settings.get('structure_priocolor')
TEXTCOLOR = settings.get('structure_textcolor')
CTEXTCOLOR = settings.get('structure_ctextcolor')
EXPCOLOR = settings.get('structure_expcolor')
COLCOLOR = settings.get('structure_colcolor')
ECBORDERCOLOR = settings.get('structure_ecbordercolor')

LEAFCOLOR_NOPLAY = settings.get('structure_darkleaf')
RPCOLOR_NOPLAY = settings.get('structure_darkrp')
SLIDECOLOR_NOPLAY = settings.get('structure_darkslide')
BAGCOLOR_NOPLAY = settings.get('structure_darkbag')
ALTCOLOR_NOPLAY = settings.get('structure_darkalt')
PARCOLOR_NOPLAY = settings.get('structure_darkpar')
SEQCOLOR_NOPLAY = settings.get('structure_darkseq')
EXCLCOLOR_NOPLAY = settings.get('structure_darkexcl')
PRIOCOLOR_NOPLAY = settings.get('structure_darkprio')

# Focus color assignments (from light to dark gray)

FOCUSLEFT = settings.get('structure_focusleft')
FOCUSTOP = settings.get('structure_focustop')
FOCUSRIGHT = settings.get('structure_focusright')
FOCUSBOTTOM = settings.get('structure_focusbottom')
