#if !defined(AFX_REALAUDIO_H__7F747BE1_DBCF_11D2_A633_00A0246BC0BD__INCLUDED_)
#define AFX_REALAUDIO_H__7F747BE1_DBCF_11D2_A633_00A0246BC0BD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRealAudio wrapper class

class CRealAudio : public CWnd
{
protected:
	DECLARE_DYNCREATE(CRealAudio)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xcfcdaa03, 0x8be4, 0x11cf, { 0xb8, 0x4b, 0x0, 0x20, 0xaf, 0xbb, 0xcc, 0xfa } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetSource();
	void SetSource(LPCTSTR lpszNewValue);
	CString GetConsole();
	void SetConsole(LPCTSTR lpszNewValue);
	CString GetControls();
	void SetControls(LPCTSTR lpszNewValue);
	BOOL GetNoLabels();
	void SetNoLabels(BOOL bNewValue);
	BOOL GetAutoStart();
	void SetAutoStart(BOOL bNewValue);
	BOOL GetAutoGotoURL();
	void SetAutoGotoURL(BOOL bNewValue);
	CString GetWindowName();
	void SetWindowName(LPCTSTR lpszNewValue);
	void DoPlayPause();
	void DoStop();
	void DoNextItem();
	void DoPrevItem();
	BOOL CanPlayPause();
	BOOL CanStop();
	BOOL HasNextItem();
	BOOL HasPrevItem();
	void AboutBox();
	void EditPreferences();
	void HideShowStatistics();
	BOOL IsStatisticsVisible();
	void DoGotoURL(LPCTSTR url, LPCTSTR target);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_REALAUDIO_H__7F747BE1_DBCF_11D2_A633_00A0246BC0BD__INCLUDED_)
