
import java.awt.*;
import javax.swing.*;

public class JDialogOpen extends javax.swing.JDialog
{
	int result = 0;
	String text = "";
    
	public JDialogOpen(Frame parent)
	{
		super(parent, "Open document", true);
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Open document");
		getContentPane().setLayout(null);
		setSize(575,116);
		setVisible(false);
		getContentPane().add(JTextField1);
		JTextField1.setBounds(78,20,480,22);
		JButtonOpen.setText("Open");
		JButtonOpen.setActionCommand("Open");
		getContentPane().add(JButtonOpen);
		JButtonOpen.setBounds(304,64,106,32);
		JButtonCancel.setText("Cancel");
		JButtonCancel.setActionCommand("Cancel");
		getContentPane().add(JButtonCancel);
		JButtonCancel.setBounds(452,62,106,32);
		JLabel1.setText("File ot URL:");
		getContentPane().add(JLabel1);
		JLabel1.setBackground(new java.awt.Color(204,204,204));
		JLabel1.setForeground(java.awt.Color.black);
		JLabel1.setFont(new Font("Dialog", Font.BOLD, 12));
		JLabel1.setBounds(10,18,62,26);
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		JButtonOpen.addActionListener(lSymAction);
		JButtonCancel.addActionListener(lSymAction);
		SymKey aSymKey = new SymKey();
		JTextField1.addKeyListener(aSymKey);
		//}}
	}

	public JDialogOpen()
	{
		this((Frame)null);
	}

	public JDialogOpen(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(200, 100);
		super.setVisible(b);
	}

    void setText(String text){
        JTextField1.setText(text);
    }
    
	static public void main(String args[])
	{
		(new JDialogOpen()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JTextField JTextField1 = new javax.swing.JTextField();
	javax.swing.JButton JButtonOpen = new javax.swing.JButton();
	javax.swing.JButton JButtonCancel = new javax.swing.JButton();
	javax.swing.JLabel JLabel1 = new javax.swing.JLabel();
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == JButtonOpen)
				JButtonOpen_actionPerformed(event);
			else if (object == JButtonCancel)
				JButtonCancel_actionPerformed(event);
		}
	}

	void JButtonOpen_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		result = 1;	 
		text = JTextField1.getText();
		dispose();
	}

	void JButtonCancel_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		dispose();
			 
	}
	
	class SymKey extends java.awt.event.KeyAdapter
	{
		public void keyTyped(java.awt.event.KeyEvent event)
		{
			Object object = event.getSource();
			if (object == JTextField1)
				JTextField1_keyTyped(event);
		}
	}

	void JTextField1_keyTyped(java.awt.event.KeyEvent event)
	{
		if(event.getKeyChar()=='\n' || event.getKeyChar()=='\r'){
		    result = 1;	 
		    text = JTextField1.getText();
		    //setVisible(false);
		    dispose();
		}
			 
	}
}