/* this ALWAYS GENERATED file contains the definitions for the interfaces */


/* File created by MIDL compiler version 3.01.75 */
/* at Fri Dec 03 17:05:17 1999
 */
/* Compiler settings for .\nssauthen.idl:
    Os (OptLev=s), W1, Zp8, env=Win32, ms_ext, c_ext
    error checks: none
*/
//@@MIDL_FILE_HEADING(  )
#include "rpc.h"
#include "rpcndr.h"
#ifndef COM_NO_WINDOWS_H
#include "windows.h"
#include "ole2.h"
#endif /*COM_NO_WINDOWS_H*/

#ifndef __nssauthen_h__
#define __nssauthen_h__

#ifdef __cplusplus
extern "C"{
#endif 

/* Forward Declarations */ 

#ifndef __INSSAuthenticationCallback_FWD_DEFINED__
#define __INSSAuthenticationCallback_FWD_DEFINED__
typedef interface INSSAuthenticationCallback INSSAuthenticationCallback;
#endif 	/* __INSSAuthenticationCallback_FWD_DEFINED__ */


#ifndef __INSSAuthenticator_FWD_DEFINED__
#define __INSSAuthenticator_FWD_DEFINED__
typedef interface INSSAuthenticator INSSAuthenticator;
#endif 	/* __INSSAuthenticator_FWD_DEFINED__ */


#ifndef __INSSUserAuthentication_FWD_DEFINED__
#define __INSSUserAuthentication_FWD_DEFINED__
typedef interface INSSUserAuthentication INSSUserAuthentication;
#endif 	/* __INSSUserAuthentication_FWD_DEFINED__ */


/* header files for imported files */
#include "oaidl.h"
#include "ocidl.h"
#include "nsscore.h"

void __RPC_FAR * __RPC_USER MIDL_user_allocate(size_t);
void __RPC_USER MIDL_user_free( void __RPC_FAR * ); 

/****************************************
 * Generated header for interface: __MIDL_itf_nssauthen_0000
 * at Fri Dec 03 17:05:17 1999
 * using MIDL 3.01.75
 ****************************************/
/* [local] */ 


//+-------------------------------------------------------------------------
//
//  Microsoft NetShow
//  Copyright (C) Microsoft Corporation 1998.
//
//  Automatically generated by Midl from nssauthen.idl
//
//  DO NOT EDIT THIS FILE.
//
//--------------------------------------------------------------------------

typedef 
enum NS_AUTH_RESULT
    {	NS_AUTH_SUCCESS	= 0x1,
	NS_AUTH_DENIED	= 0x2,
	NS_AUTH_CONTINUE	= 0x3,
	NS_AUTH_ERROR	= 0x4,
	NS_AUTH_PENDING	= 0x5,
	NS_AUTH_NONE	= 0x6,
	NS_AUTH_START	= 0x7
    }	NS_AUTH_RESULT;

typedef 
enum NS_AUTH_FLAGS
    {	NS_TEXT_WIRE_PROTOCOL	= 0x1
    }	NS_AUTH_FLAGS;



extern RPC_IF_HANDLE __MIDL_itf_nssauthen_0000_v0_0_c_ifspec;
extern RPC_IF_HANDLE __MIDL_itf_nssauthen_0000_v0_0_s_ifspec;

#ifndef __INSSAuthenticationCallback_INTERFACE_DEFINED__
#define __INSSAuthenticationCallback_INTERFACE_DEFINED__

/****************************************
 * Generated header for interface: INSSAuthenticationCallback
 * at Fri Dec 03 17:05:17 1999
 * using MIDL 3.01.75
 ****************************************/
/* [unique][version][uuid][object] */ 



EXTERN_C const IID IID_INSSAuthenticationCallback;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    interface DECLSPEC_UUID("6bf5dfc4-1b4d-11d1-9312-00c04fd919b7")
    INSSAuthenticationCallback : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE OnAuthenticateComplete( 
            /* [in] */ NS_AUTH_RESULT Result,
            /* [in] */ INSSUserAuthentication __RPC_FAR *pUserCredential,
            /* [in] */ DWORD dwRequestId) = 0;
        
    };
    
#else 	/* C style interface */

    typedef struct INSSAuthenticationCallbackVtbl
    {
        BEGIN_INTERFACE
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *QueryInterface )( 
            INSSAuthenticationCallback __RPC_FAR * This,
            /* [in] */ REFIID riid,
            /* [iid_is][out] */ void __RPC_FAR *__RPC_FAR *ppvObject);
        
        ULONG ( STDMETHODCALLTYPE __RPC_FAR *AddRef )( 
            INSSAuthenticationCallback __RPC_FAR * This);
        
        ULONG ( STDMETHODCALLTYPE __RPC_FAR *Release )( 
            INSSAuthenticationCallback __RPC_FAR * This);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *OnAuthenticateComplete )( 
            INSSAuthenticationCallback __RPC_FAR * This,
            /* [in] */ NS_AUTH_RESULT Result,
            /* [in] */ INSSUserAuthentication __RPC_FAR *pUserCredential,
            /* [in] */ DWORD dwRequestId);
        
        END_INTERFACE
    } INSSAuthenticationCallbackVtbl;

    interface INSSAuthenticationCallback
    {
        CONST_VTBL struct INSSAuthenticationCallbackVtbl __RPC_FAR *lpVtbl;
    };

    

#ifdef COBJMACROS


#define INSSAuthenticationCallback_QueryInterface(This,riid,ppvObject)	\
    (This)->lpVtbl -> QueryInterface(This,riid,ppvObject)

#define INSSAuthenticationCallback_AddRef(This)	\
    (This)->lpVtbl -> AddRef(This)

#define INSSAuthenticationCallback_Release(This)	\
    (This)->lpVtbl -> Release(This)


#define INSSAuthenticationCallback_OnAuthenticateComplete(This,Result,pUserCredential,dwRequestId)	\
    (This)->lpVtbl -> OnAuthenticateComplete(This,Result,pUserCredential,dwRequestId)

#endif /* COBJMACROS */


#endif 	/* C style interface */



HRESULT STDMETHODCALLTYPE INSSAuthenticationCallback_OnAuthenticateComplete_Proxy( 
    INSSAuthenticationCallback __RPC_FAR * This,
    /* [in] */ NS_AUTH_RESULT Result,
    /* [in] */ INSSUserAuthentication __RPC_FAR *pUserCredential,
    /* [in] */ DWORD dwRequestId);


void __RPC_STUB INSSAuthenticationCallback_OnAuthenticateComplete_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);



#endif 	/* __INSSAuthenticationCallback_INTERFACE_DEFINED__ */


#ifndef __INSSAuthenticator_INTERFACE_DEFINED__
#define __INSSAuthenticator_INTERFACE_DEFINED__

/****************************************
 * Generated header for interface: INSSAuthenticator
 * at Fri Dec 03 17:05:17 1999
 * using MIDL 3.01.75
 ****************************************/
/* [unique][version][uuid][object] */ 



EXTERN_C const IID IID_INSSAuthenticator;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    interface DECLSPEC_UUID("cb27d5e6-3778-11d1-8c96-00a0c903a1a2")
    INSSAuthenticator : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE Initialize( 
            /* [in] */ INSSServerContext __RPC_FAR *pServerContext,
            /* [out] */ DWORD __RPC_FAR *dwFlags,
            /* [out] */ LPBSTR pbstrDefaultRealm) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE CreateUserAuthentication( 
            /* [out] */ INSSUserAuthentication __RPC_FAR *__RPC_FAR *ppUserAuthen) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetAuthenticationType( 
            /* [out] */ LPBSTR bstrAuthenType) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetAuthenticatorClass( 
            /* [out] */ GUID __RPC_FAR *pCLSID) = 0;
        
    };
    
#else 	/* C style interface */

    typedef struct INSSAuthenticatorVtbl
    {
        BEGIN_INTERFACE
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *QueryInterface )( 
            INSSAuthenticator __RPC_FAR * This,
            /* [in] */ REFIID riid,
            /* [iid_is][out] */ void __RPC_FAR *__RPC_FAR *ppvObject);
        
        ULONG ( STDMETHODCALLTYPE __RPC_FAR *AddRef )( 
            INSSAuthenticator __RPC_FAR * This);
        
        ULONG ( STDMETHODCALLTYPE __RPC_FAR *Release )( 
            INSSAuthenticator __RPC_FAR * This);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *Initialize )( 
            INSSAuthenticator __RPC_FAR * This,
            /* [in] */ INSSServerContext __RPC_FAR *pServerContext,
            /* [out] */ DWORD __RPC_FAR *dwFlags,
            /* [out] */ LPBSTR pbstrDefaultRealm);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *CreateUserAuthentication )( 
            INSSAuthenticator __RPC_FAR * This,
            /* [out] */ INSSUserAuthentication __RPC_FAR *__RPC_FAR *ppUserAuthen);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *GetAuthenticationType )( 
            INSSAuthenticator __RPC_FAR * This,
            /* [out] */ LPBSTR bstrAuthenType);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *GetAuthenticatorClass )( 
            INSSAuthenticator __RPC_FAR * This,
            /* [out] */ GUID __RPC_FAR *pCLSID);
        
        END_INTERFACE
    } INSSAuthenticatorVtbl;

    interface INSSAuthenticator
    {
        CONST_VTBL struct INSSAuthenticatorVtbl __RPC_FAR *lpVtbl;
    };

    

#ifdef COBJMACROS


#define INSSAuthenticator_QueryInterface(This,riid,ppvObject)	\
    (This)->lpVtbl -> QueryInterface(This,riid,ppvObject)

#define INSSAuthenticator_AddRef(This)	\
    (This)->lpVtbl -> AddRef(This)

#define INSSAuthenticator_Release(This)	\
    (This)->lpVtbl -> Release(This)


#define INSSAuthenticator_Initialize(This,pServerContext,dwFlags,pbstrDefaultRealm)	\
    (This)->lpVtbl -> Initialize(This,pServerContext,dwFlags,pbstrDefaultRealm)

#define INSSAuthenticator_CreateUserAuthentication(This,ppUserAuthen)	\
    (This)->lpVtbl -> CreateUserAuthentication(This,ppUserAuthen)

#define INSSAuthenticator_GetAuthenticationType(This,bstrAuthenType)	\
    (This)->lpVtbl -> GetAuthenticationType(This,bstrAuthenType)

#define INSSAuthenticator_GetAuthenticatorClass(This,pCLSID)	\
    (This)->lpVtbl -> GetAuthenticatorClass(This,pCLSID)

#endif /* COBJMACROS */


#endif 	/* C style interface */



HRESULT STDMETHODCALLTYPE INSSAuthenticator_Initialize_Proxy( 
    INSSAuthenticator __RPC_FAR * This,
    /* [in] */ INSSServerContext __RPC_FAR *pServerContext,
    /* [out] */ DWORD __RPC_FAR *dwFlags,
    /* [out] */ LPBSTR pbstrDefaultRealm);


void __RPC_STUB INSSAuthenticator_Initialize_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


HRESULT STDMETHODCALLTYPE INSSAuthenticator_CreateUserAuthentication_Proxy( 
    INSSAuthenticator __RPC_FAR * This,
    /* [out] */ INSSUserAuthentication __RPC_FAR *__RPC_FAR *ppUserAuthen);


void __RPC_STUB INSSAuthenticator_CreateUserAuthentication_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


HRESULT STDMETHODCALLTYPE INSSAuthenticator_GetAuthenticationType_Proxy( 
    INSSAuthenticator __RPC_FAR * This,
    /* [out] */ LPBSTR bstrAuthenType);


void __RPC_STUB INSSAuthenticator_GetAuthenticationType_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


HRESULT STDMETHODCALLTYPE INSSAuthenticator_GetAuthenticatorClass_Proxy( 
    INSSAuthenticator __RPC_FAR * This,
    /* [out] */ GUID __RPC_FAR *pCLSID);


void __RPC_STUB INSSAuthenticator_GetAuthenticatorClass_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);



#endif 	/* __INSSAuthenticator_INTERFACE_DEFINED__ */


#ifndef __INSSUserAuthentication_INTERFACE_DEFINED__
#define __INSSUserAuthentication_INTERFACE_DEFINED__

/****************************************
 * Generated header for interface: INSSUserAuthentication
 * at Fri Dec 03 17:05:17 1999
 * using MIDL 3.01.75
 ****************************************/
/* [unique][version][uuid][object] */ 



EXTERN_C const IID IID_INSSUserAuthentication;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    interface DECLSPEC_UUID("48eea71a-3775-11d1-8c96-00a0c903a1a2")
    INSSUserAuthentication : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE Authenticate( 
            /* [in] */ DWORD cbBlob,
            /* [size_is][in] */ BYTE __RPC_FAR *pBlob,
            /* [in] */ INSSCommandContext __RPC_FAR *pCommandContext,
            /* [in] */ INSSAuthenticationCallback __RPC_FAR *pCallback,
            /* [in] */ DWORD dwRequestId) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetChallenge( 
            /* [out] */ DWORD __RPC_FAR *pcbBlob,
            /* [size_is][size_is][out] */ BYTE __RPC_FAR *__RPC_FAR *pBlob,
            /* [out] */ LPBSTR pbstrRealm) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetAuthenticator( 
            /* [out] */ INSSAuthenticator __RPC_FAR *__RPC_FAR *pAuth) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetAuthenticationResult( 
            /* [out] */ NS_AUTH_RESULT __RPC_FAR *pResult) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetUserId( 
            /* [out] */ BSTR __RPC_FAR *pbstrUserId) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE Impersonate( void) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE Revert( void) = 0;
        
    };
    
#else 	/* C style interface */

    typedef struct INSSUserAuthenticationVtbl
    {
        BEGIN_INTERFACE
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *QueryInterface )( 
            INSSUserAuthentication __RPC_FAR * This,
            /* [in] */ REFIID riid,
            /* [iid_is][out] */ void __RPC_FAR *__RPC_FAR *ppvObject);
        
        ULONG ( STDMETHODCALLTYPE __RPC_FAR *AddRef )( 
            INSSUserAuthentication __RPC_FAR * This);
        
        ULONG ( STDMETHODCALLTYPE __RPC_FAR *Release )( 
            INSSUserAuthentication __RPC_FAR * This);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *Authenticate )( 
            INSSUserAuthentication __RPC_FAR * This,
            /* [in] */ DWORD cbBlob,
            /* [size_is][in] */ BYTE __RPC_FAR *pBlob,
            /* [in] */ INSSCommandContext __RPC_FAR *pCommandContext,
            /* [in] */ INSSAuthenticationCallback __RPC_FAR *pCallback,
            /* [in] */ DWORD dwRequestId);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *GetChallenge )( 
            INSSUserAuthentication __RPC_FAR * This,
            /* [out] */ DWORD __RPC_FAR *pcbBlob,
            /* [size_is][size_is][out] */ BYTE __RPC_FAR *__RPC_FAR *pBlob,
            /* [out] */ LPBSTR pbstrRealm);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *GetAuthenticator )( 
            INSSUserAuthentication __RPC_FAR * This,
            /* [out] */ INSSAuthenticator __RPC_FAR *__RPC_FAR *pAuth);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *GetAuthenticationResult )( 
            INSSUserAuthentication __RPC_FAR * This,
            /* [out] */ NS_AUTH_RESULT __RPC_FAR *pResult);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *GetUserId )( 
            INSSUserAuthentication __RPC_FAR * This,
            /* [out] */ BSTR __RPC_FAR *pbstrUserId);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *Impersonate )( 
            INSSUserAuthentication __RPC_FAR * This);
        
        HRESULT ( STDMETHODCALLTYPE __RPC_FAR *Revert )( 
            INSSUserAuthentication __RPC_FAR * This);
        
        END_INTERFACE
    } INSSUserAuthenticationVtbl;

    interface INSSUserAuthentication
    {
        CONST_VTBL struct INSSUserAuthenticationVtbl __RPC_FAR *lpVtbl;
    };

    

#ifdef COBJMACROS


#define INSSUserAuthentication_QueryInterface(This,riid,ppvObject)	\
    (This)->lpVtbl -> QueryInterface(This,riid,ppvObject)

#define INSSUserAuthentication_AddRef(This)	\
    (This)->lpVtbl -> AddRef(This)

#define INSSUserAuthentication_Release(This)	\
    (This)->lpVtbl -> Release(This)


#define INSSUserAuthentication_Authenticate(This,cbBlob,pBlob,pCommandContext,pCallback,dwRequestId)	\
    (This)->lpVtbl -> Authenticate(This,cbBlob,pBlob,pCommandContext,pCallback,dwRequestId)

#define INSSUserAuthentication_GetChallenge(This,pcbBlob,pBlob,pbstrRealm)	\
    (This)->lpVtbl -> GetChallenge(This,pcbBlob,pBlob,pbstrRealm)

#define INSSUserAuthentication_GetAuthenticator(This,pAuth)	\
    (This)->lpVtbl -> GetAuthenticator(This,pAuth)

#define INSSUserAuthentication_GetAuthenticationResult(This,pResult)	\
    (This)->lpVtbl -> GetAuthenticationResult(This,pResult)

#define INSSUserAuthentication_GetUserId(This,pbstrUserId)	\
    (This)->lpVtbl -> GetUserId(This,pbstrUserId)

#define INSSUserAuthentication_Impersonate(This)	\
    (This)->lpVtbl -> Impersonate(This)

#define INSSUserAuthentication_Revert(This)	\
    (This)->lpVtbl -> Revert(This)

#endif /* COBJMACROS */


#endif 	/* C style interface */



HRESULT STDMETHODCALLTYPE INSSUserAuthentication_Authenticate_Proxy( 
    INSSUserAuthentication __RPC_FAR * This,
    /* [in] */ DWORD cbBlob,
    /* [size_is][in] */ BYTE __RPC_FAR *pBlob,
    /* [in] */ INSSCommandContext __RPC_FAR *pCommandContext,
    /* [in] */ INSSAuthenticationCallback __RPC_FAR *pCallback,
    /* [in] */ DWORD dwRequestId);


void __RPC_STUB INSSUserAuthentication_Authenticate_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


HRESULT STDMETHODCALLTYPE INSSUserAuthentication_GetChallenge_Proxy( 
    INSSUserAuthentication __RPC_FAR * This,
    /* [out] */ DWORD __RPC_FAR *pcbBlob,
    /* [size_is][size_is][out] */ BYTE __RPC_FAR *__RPC_FAR *pBlob,
    /* [out] */ LPBSTR pbstrRealm);


void __RPC_STUB INSSUserAuthentication_GetChallenge_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


HRESULT STDMETHODCALLTYPE INSSUserAuthentication_GetAuthenticator_Proxy( 
    INSSUserAuthentication __RPC_FAR * This,
    /* [out] */ INSSAuthenticator __RPC_FAR *__RPC_FAR *pAuth);


void __RPC_STUB INSSUserAuthentication_GetAuthenticator_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


HRESULT STDMETHODCALLTYPE INSSUserAuthentication_GetAuthenticationResult_Proxy( 
    INSSUserAuthentication __RPC_FAR * This,
    /* [out] */ NS_AUTH_RESULT __RPC_FAR *pResult);


void __RPC_STUB INSSUserAuthentication_GetAuthenticationResult_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


HRESULT STDMETHODCALLTYPE INSSUserAuthentication_GetUserId_Proxy( 
    INSSUserAuthentication __RPC_FAR * This,
    /* [out] */ BSTR __RPC_FAR *pbstrUserId);


void __RPC_STUB INSSUserAuthentication_GetUserId_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


HRESULT STDMETHODCALLTYPE INSSUserAuthentication_Impersonate_Proxy( 
    INSSUserAuthentication __RPC_FAR * This);


void __RPC_STUB INSSUserAuthentication_Impersonate_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


HRESULT STDMETHODCALLTYPE INSSUserAuthentication_Revert_Proxy( 
    INSSUserAuthentication __RPC_FAR * This);


void __RPC_STUB INSSUserAuthentication_Revert_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);



#endif 	/* __INSSUserAuthentication_INTERFACE_DEFINED__ */


/* Additional Prototypes for ALL interfaces */

unsigned long             __RPC_USER  BSTR_UserSize(     unsigned long __RPC_FAR *, unsigned long            , BSTR __RPC_FAR * ); 
unsigned char __RPC_FAR * __RPC_USER  BSTR_UserMarshal(  unsigned long __RPC_FAR *, unsigned char __RPC_FAR *, BSTR __RPC_FAR * ); 
unsigned char __RPC_FAR * __RPC_USER  BSTR_UserUnmarshal(unsigned long __RPC_FAR *, unsigned char __RPC_FAR *, BSTR __RPC_FAR * ); 
void                      __RPC_USER  BSTR_UserFree(     unsigned long __RPC_FAR *, BSTR __RPC_FAR * ); 

/* end of Additional Prototypes */

#ifdef __cplusplus
}
#endif

#endif
