#if !defined(AFX_DOMATTRIBUTE_H__D45C1CBE_212B_4E01_A4C0_75492C0098F4__INCLUDED_)
#define AFX_DOMATTRIBUTE_H__D45C1CBE_212B_4E01_A4C0_75492C0098F4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDOMNode;
class CDOMNodeList;
class CDOMNamedNodeMap;
class CDOMDocument;

/////////////////////////////////////////////////////////////////////////////
// CDOMAttribute wrapper class

class CDOMAttribute : public COleDispatchDriver
{
public:
	CDOMAttribute() {}		// Calls COleDispatchDriver default constructor
	CDOMAttribute(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDOMAttribute(const CDOMAttribute& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetNodeName();
	VARIANT GetNodeValue();
	void SetNodeValue(const VARIANT& newValue);
	long GetNodeType();
	CDOMNode GetParentNode();
	CDOMNodeList GetChildNodes();
	CDOMNode GetFirstChild();
	CDOMNode GetLastChild();
	CDOMNode GetPreviousSibling();
	CDOMNode GetNextSibling();
	CDOMNamedNodeMap GetAttributes();
	CDOMNode insertBefore(LPDISPATCH newChild, const VARIANT& refChild);
	CDOMNode replaceChild(LPDISPATCH newChild, LPDISPATCH oldChild);
	CDOMNode removeChild(LPDISPATCH childNode);
	CDOMNode appendChild(LPDISPATCH newChild);
	BOOL hasChildNodes();
	CDOMDocument GetOwnerDocument();
	CDOMNode cloneNode(BOOL deep);
	CString GetName();
	BOOL GetSpecified();
	VARIANT GetValue();
	void SetValue(const VARIANT& newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DOMATTRIBUTE_H__D45C1CBE_212B_4E01_A4C0_75492C0098F4__INCLUDED_)
