#if !defined(AFX_DOMCDATASECTION_H__2662176D_0AFE_4BF6_B5D2_930EB84524D0__INCLUDED_)
#define AFX_DOMCDATASECTION_H__2662176D_0AFE_4BF6_B5D2_930EB84524D0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDOMNode;
class CDOMNodeList;
class CDOMNamedNodeMap;
class CDOMDocument;
class CDOMText;

/////////////////////////////////////////////////////////////////////////////
// CDOMCDATASection wrapper class

class CDOMCDATASection : public COleDispatchDriver
{
public:
	CDOMCDATASection() {}		// Calls COleDispatchDriver default constructor
	CDOMCDATASection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDOMCDATASection(const CDOMCDATASection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetNodeName();
	VARIANT GetNodeValue();
	void SetNodeValue(const VARIANT& newValue);
	long GetNodeType();
	CDOMNode GetParentNode();
	CDOMNodeList GetChildNodes();
	CDOMNode GetFirstChild();
	CDOMNode GetLastChild();
	CDOMNode GetPreviousSibling();
	CDOMNode GetNextSibling();
	CDOMNamedNodeMap GetAttributes();
	CDOMNode insertBefore(LPDISPATCH newChild, const VARIANT& refChild);
	CDOMNode replaceChild(LPDISPATCH newChild, LPDISPATCH oldChild);
	CDOMNode removeChild(LPDISPATCH childNode);
	CDOMNode appendChild(LPDISPATCH newChild);
	BOOL hasChildNodes();
	CDOMDocument GetOwnerDocument();
	CDOMNode cloneNode(BOOL deep);
	CString GetData();
	void SetData(LPCTSTR lpszNewValue);
	long GetLength();
	CString substringData(long offset, long count);
	void appendData(LPCTSTR data);
	void insertData(long offset, LPCTSTR data);
	void deleteData(long offset, long count);
	void replaceData(long offset, long count, LPCTSTR data);
	CDOMText splitText(long offset);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DOMCDATASECTION_H__2662176D_0AFE_4BF6_B5D2_930EB84524D0__INCLUDED_)
