#if !defined(AFX_DOMDOCUMENT_H__218BA1E1_53E9_4932_AC52_A7EB1ED6BBF7__INCLUDED_)
#define AFX_DOMDOCUMENT_H__218BA1E1_53E9_4932_AC52_A7EB1ED6BBF7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDOMNode;
class CDOMNodeList;
class CDOMNamedNodeMap;
class CDOMDocumentType;
class CDOMImplementation;
class CDOMElement;
class CDOMDocumentFragment;
class CDOMText;
class CDOMComment;
class CDOMCDATASection;
class CDOMProcessingInstruction;
class CDOMAttribute;
class CDOMEntityReference;

/////////////////////////////////////////////////////////////////////////////
// CDOMDocument wrapper class

class CDOMDocument : public COleDispatchDriver
{
public:
	CDOMDocument() {}		// Calls COleDispatchDriver default constructor
	CDOMDocument(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDOMDocument(const CDOMDocument& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetNodeName();
	VARIANT GetNodeValue();
	void SetNodeValue(const VARIANT& newValue);
	long GetNodeType();
	CDOMNode GetParentNode();
	CDOMNodeList GetChildNodes();
	CDOMNode GetFirstChild();
	CDOMNode GetLastChild();
	CDOMNode GetPreviousSibling();
	CDOMNode GetNextSibling();
	CDOMNamedNodeMap GetAttributes();
	CDOMNode insertBefore(LPDISPATCH newChild, const VARIANT& refChild);
	CDOMNode replaceChild(LPDISPATCH newChild, LPDISPATCH oldChild);
	CDOMNode removeChild(LPDISPATCH childNode);
	CDOMNode appendChild(LPDISPATCH newChild);
	BOOL hasChildNodes();
	CDOMDocument GetOwnerDocument();
	CDOMNode cloneNode(BOOL deep);
	CDOMDocumentType GetDoctype();
	CDOMImplementation GetImplementation();
	CDOMElement GetDocumentElement();
	void SetRefDocumentElement(LPDISPATCH newValue);
	CDOMElement createElement(LPCTSTR tagName);
	CDOMDocumentFragment createDocumentFragment();
	CDOMText createTextNode(LPCTSTR data);
	CDOMComment createComment(LPCTSTR data);
	CDOMCDATASection createCDATASection(LPCTSTR data);
	CDOMProcessingInstruction createProcessingInstruction(LPCTSTR target, LPCTSTR data);
	CDOMAttribute createAttribute(LPCTSTR name);
	CDOMEntityReference createEntityReference(LPCTSTR name);
	CDOMNodeList getElementsByTagName(LPCTSTR tagName);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DOMDOCUMENT_H__218BA1E1_53E9_4932_AC52_A7EB1ED6BBF7__INCLUDED_)
