#if !defined(AFX_DOMDOCUMENTTYPE_H__E6DF275C_F9A5_4EA8_A10D_7C15A06755E3__INCLUDED_)
#define AFX_DOMDOCUMENTTYPE_H__E6DF275C_F9A5_4EA8_A10D_7C15A06755E3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDOMNode;
class CDOMNodeList;
class CDOMNamedNodeMap;
class CDOMDocument;

/////////////////////////////////////////////////////////////////////////////
// CDOMDocumentType wrapper class

class CDOMDocumentType : public COleDispatchDriver
{
public:
	CDOMDocumentType() {}		// Calls COleDispatchDriver default constructor
	CDOMDocumentType(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDOMDocumentType(const CDOMDocumentType& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetNodeName();
	VARIANT GetNodeValue();
	void SetNodeValue(const VARIANT& newValue);
	long GetNodeType();
	CDOMNode GetParentNode();
	CDOMNodeList GetChildNodes();
	CDOMNode GetFirstChild();
	CDOMNode GetLastChild();
	CDOMNode GetPreviousSibling();
	CDOMNode GetNextSibling();
	CDOMNamedNodeMap GetAttributes();
	CDOMNode insertBefore(LPDISPATCH newChild, const VARIANT& refChild);
	CDOMNode replaceChild(LPDISPATCH newChild, LPDISPATCH oldChild);
	CDOMNode removeChild(LPDISPATCH childNode);
	CDOMNode appendChild(LPDISPATCH newChild);
	BOOL hasChildNodes();
	CDOMDocument GetOwnerDocument();
	CDOMNode cloneNode(BOOL deep);
	CString GetName();
	CDOMNamedNodeMap GetEntities();
	CDOMNamedNodeMap GetNotations();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DOMDOCUMENTTYPE_H__E6DF275C_F9A5_4EA8_A10D_7C15A06755E3__INCLUDED_)
