#if !defined(AFX_DOMELEMENT_H__8B2C8A72_F770_4B42_B770_14703BC1AE68__INCLUDED_)
#define AFX_DOMELEMENT_H__8B2C8A72_F770_4B42_B770_14703BC1AE68__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDOMNode;
class CDOMNodeList;
class CDOMNamedNodeMap;
class CDOMDocument;
class CDOMAttribute;

/////////////////////////////////////////////////////////////////////////////
// CDOMElement wrapper class

class CDOMElement : public COleDispatchDriver
{
public:
	CDOMElement() {}		// Calls COleDispatchDriver default constructor
	CDOMElement(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDOMElement(const CDOMElement& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetNodeName();
	VARIANT GetNodeValue();
	void SetNodeValue(const VARIANT& newValue);
	long GetNodeType();
	CDOMNode GetParentNode();
	CDOMNodeList GetChildNodes();
	CDOMNode GetFirstChild();
	CDOMNode GetLastChild();
	CDOMNode GetPreviousSibling();
	CDOMNode GetNextSibling();
	CDOMNamedNodeMap GetAttributes();
	CDOMNode insertBefore(LPDISPATCH newChild, const VARIANT& refChild);
	CDOMNode replaceChild(LPDISPATCH newChild, LPDISPATCH oldChild);
	CDOMNode removeChild(LPDISPATCH childNode);
	CDOMNode appendChild(LPDISPATCH newChild);
	BOOL hasChildNodes();
	CDOMDocument GetOwnerDocument();
	CDOMNode cloneNode(BOOL deep);
	CString GetTagName();
	VARIANT getAttribute(LPCTSTR name);
	void setAttribute(LPCTSTR name, const VARIANT& value);
	void removeAttribute(LPCTSTR name);
	CDOMAttribute getAttributeNode(LPCTSTR name);
	CDOMAttribute setAttributeNode(LPDISPATCH DOMAttribute);
	CDOMAttribute removeAttributeNode(LPDISPATCH DOMAttribute);
	CDOMNodeList getElementsByTagName(LPCTSTR tagName);
	void normalize();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DOMELEMENT_H__8B2C8A72_F770_4B42_B770_14703BC1AE68__INCLUDED_)
