#if !defined(AFX_DOMENTITYREFERENCE_H__1BE3B9B4_5D18_418B_A9E4_812BCF83910F__INCLUDED_)
#define AFX_DOMENTITYREFERENCE_H__1BE3B9B4_5D18_418B_A9E4_812BCF83910F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDOMNode;
class CDOMNodeList;
class CDOMNamedNodeMap;
class CDOMDocument;

/////////////////////////////////////////////////////////////////////////////
// CDOMEntityReference wrapper class

class CDOMEntityReference : public COleDispatchDriver
{
public:
	CDOMEntityReference() {}		// Calls COleDispatchDriver default constructor
	CDOMEntityReference(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDOMEntityReference(const CDOMEntityReference& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetNodeName();
	VARIANT GetNodeValue();
	void SetNodeValue(const VARIANT& newValue);
	long GetNodeType();
	CDOMNode GetParentNode();
	CDOMNodeList GetChildNodes();
	CDOMNode GetFirstChild();
	CDOMNode GetLastChild();
	CDOMNode GetPreviousSibling();
	CDOMNode GetNextSibling();
	CDOMNamedNodeMap GetAttributes();
	CDOMNode insertBefore(LPDISPATCH newChild, const VARIANT& refChild);
	CDOMNode replaceChild(LPDISPATCH newChild, LPDISPATCH oldChild);
	CDOMNode removeChild(LPDISPATCH childNode);
	CDOMNode appendChild(LPDISPATCH newChild);
	BOOL hasChildNodes();
	CDOMDocument GetOwnerDocument();
	CDOMNode cloneNode(BOOL deep);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DOMENTITYREFERENCE_H__1BE3B9B4_5D18_418B_A9E4_812BCF83910F__INCLUDED_)
