#if !defined(AFX_DOMNODELIST_H__0B89ED79_44CF_43DA_B0D8_627EDC733976__INCLUDED_)
#define AFX_DOMNODELIST_H__0B89ED79_44CF_43DA_B0D8_627EDC733976__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDOMNode;

/////////////////////////////////////////////////////////////////////////////
// CDOMNodeList wrapper class

class CDOMNodeList : public COleDispatchDriver
{
public:
	CDOMNodeList() {}		// Calls COleDispatchDriver default constructor
	CDOMNodeList(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDOMNodeList(const CDOMNodeList& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CDOMNode GetItem(long index);
	long GetLength();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DOMNODELIST_H__0B89ED79_44CF_43DA_B0D8_627EDC733976__INCLUDED_)
