#if !defined(AFX_DOMNAMEDNODEMAP_H__F5D6BBCD_DD46_4A09_9D5D_7018AC8C2E23__INCLUDED_)
#define AFX_DOMNAMEDNODEMAP_H__F5D6BBCD_DD46_4A09_9D5D_7018AC8C2E23__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDOMNode;

/////////////////////////////////////////////////////////////////////////////
// CDOMNamedNodeMap wrapper class

class CDOMNamedNodeMap : public COleDispatchDriver
{
public:
	CDOMNamedNodeMap() {}		// Calls COleDispatchDriver default constructor
	CDOMNamedNodeMap(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDOMNamedNodeMap(const CDOMNamedNodeMap& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CDOMNode getNamedItem(LPCTSTR name);
	CDOMNode setNamedItem(LPDISPATCH newItem);
	CDOMNode removeNamedItem(LPCTSTR name);
	CDOMNode GetItem(long index);
	long GetLength();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DOMNAMEDNODEMAP_H__F5D6BBCD_DD46_4A09_9D5D_7018AC8C2E23__INCLUDED_)
