// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "domnodelist.h"

// Dispatch interfaces referenced by this interface
#include "DOMNode.h"


/////////////////////////////////////////////////////////////////////////////
// CDOMNodeList properties

/////////////////////////////////////////////////////////////////////////////
// CDOMNodeList operations

CDOMNode CDOMNodeList::GetItem(long index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		index);
	return CDOMNode(pDispatch);
}

long CDOMNodeList::GetLength()
{
	long result;
	InvokeHelper(0x183, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}
