
package grins.demo;

import java.awt.*;
import java.awt.event.*;
import java.applet.*;
import java.io.*;

import grins.*;

public class DemoApplet extends Applet
implements SMILListener
{
    private Frame frame = null;
    
    private SMILDocument smil;
    private SMILController player;
    private SMILRenderer renderer;
    
    private Viewport viewport;
    
	public void init()
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setSize(480,132);
		buttonOpen.setLabel("Open");
		add(buttonOpen);
		buttonOpen.setBackground(java.awt.Color.lightGray);
		buttonOpen.setBounds(368,8,104,28);
		labelOpen.setText("Open:");
		add(labelOpen);
		labelOpen.setBounds(12,12,40,24);
		add(textFieldURL);
		textFieldURL.setBounds(57,8,311,28);
		buttonPlay.setLabel("Play");
		add(buttonPlay);
		buttonPlay.setBackground(java.awt.Color.lightGray);
		buttonPlay.setBounds(8,56,104,28);
		buttonPause.setLabel("Pause");
		add(buttonPause);
		buttonPause.setBackground(java.awt.Color.lightGray);
		buttonPause.setBounds(128,56,104,28);
		buttonStop.setLabel("Stop");
		add(buttonStop);
		buttonStop.setBackground(java.awt.Color.lightGray);
		buttonStop.setBounds(248,56,104,28);
		buttonClose.setLabel("Close");
		add(buttonClose);
		buttonClose.setBackground(java.awt.Color.lightGray);
		buttonClose.setBounds(368,56,104,28);
		labelDur.setText("Dur");
		add(labelDur);
		labelDur.setBounds(12,96,40,24);
		textFieldDur.setEditable(false);
		textFieldDur.setText("0");
		add(textFieldDur);
		textFieldDur.setBounds(52,96,76,24);
		labelPos.setText("Pos");
		add(labelPos);
		labelPos.setBounds(144,96,40,24);
		textFieldPos.setEditable(false);
		textFieldPos.setText("0");
		add(textFieldPos);
		textFieldPos.setBounds(184,96,76,24);
		labelSetPos.setText("SetPos");
		add(labelSetPos);
		labelSetPos.setBounds(280,96,40,24);
		textFieldSetPos.setText("0");
		add(textFieldSetPos);
		textFieldSetPos.setBounds(324,96,76,24);
		buttonSetPos.setLabel("Set Pos");
		add(buttonSetPos);
		buttonSetPos.setBackground(java.awt.Color.lightGray);
		buttonSetPos.setBounds(400,96,60,24);
		//}}
	
	    smil = GRiNSToolkit.createGRiNSDocument(this);

		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		buttonOpen.addActionListener(lSymAction);
		buttonPlay.addActionListener(lSymAction);
		buttonPause.addActionListener(lSymAction);
		buttonStop.addActionListener(lSymAction);
		buttonClose.addActionListener(lSymAction);
		buttonSetPos.addActionListener(lSymAction);
		//}}
	}
	
	//{{DECLARE_CONTROLS
	java.awt.Button buttonOpen = new java.awt.Button();
	java.awt.Label labelOpen = new java.awt.Label();
	java.awt.TextField textFieldURL = new java.awt.TextField();
	java.awt.Button buttonPlay = new java.awt.Button();
	java.awt.Button buttonPause = new java.awt.Button();
	java.awt.Button buttonStop = new java.awt.Button();
	java.awt.Button buttonClose = new java.awt.Button();
	java.awt.Label labelDur = new java.awt.Label();
	java.awt.TextField textFieldDur = new java.awt.TextField();
	java.awt.Label labelPos = new java.awt.Label();
	java.awt.TextField textFieldPos = new java.awt.TextField();
	java.awt.Label labelSetPos = new java.awt.Label();
	java.awt.TextField textFieldSetPos = new java.awt.TextField();
	java.awt.Button buttonSetPos = new java.awt.Button();
	//}}
	
	private void message(String str) {
	    System.out.println(str);
	}
	
	public void start() {
	    }
	public void stop() {
	    if(smil!=null) smil.close();
	    }
    public void destroy() {
        }
    public void setWaiting(){
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
    }
    public void setReady(){
       setCursor(Cursor.getDefaultCursor());
    }
	  
	// standalone execution support
    public static void main(String args[]) 
		{
	    class SFrame extends Frame {
	        SFrame(String title){
	            super(title);
	            }
	        void setApplet(Applet p){
	            applet = p;
	            }
	        private Applet applet;
	        }
		SFrame frame = new SFrame("Java GRiNS Player");
		frame.addWindowListener(
			new WindowAdapter() { 
				public void windowClosing(WindowEvent event) {
				    ((SFrame)event.getWindow()).applet.stop();
				    try{Thread.sleep(1000);}catch(Exception e){}
			        System.exit(0);
			        }
				});
	
		DemoApplet	demoApplet = new DemoApplet();
        frame.setApplet(demoApplet);
		demoApplet.init();
		demoApplet.start();
		frame.add("Center", demoApplet);
        frame.pack();
		frame.setSize(480+8,132+24);
		frame.setLocation(400,300);
		frame.show();
		}
	

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == buttonOpen)
				buttonOpen_ActionPerformed(event);
			else if (object == buttonPlay)
				buttonPlay_ActionPerformed(event);
			else if (object == buttonPause)
				buttonPause_ActionPerformed(event);
			else if (object == buttonStop)
				buttonStop_ActionPerformed(event);
			else if (object == buttonClose)
				buttonClose_ActionPerformed(event);
			else if (object == buttonSetPos)
				buttonSetPos_ActionPerformed(event);
		}
	}

	void buttonOpen_ActionPerformed(java.awt.event.ActionEvent event)
	{
		FileDialog dlg = new FileDialog((Frame)getParent(), "Select presentation", FileDialog.LOAD);
		dlg.show();
		String filename = dlg.getFile();
		if(filename!=null){
		    String dir  = dlg.getDirectory();
		    String absFilename = dir+filename;
		    textFieldURL.setText(absFilename);
		}
		if(smil!=null){
		    smil.open(textFieldURL.getText());
	    }
		
	}

    // implement interface of SMILListener
    public void opened(){
        Dimension d=null;
        try {d=smil.getViewportSize();}
	    catch(Exception e){System.out.println(""+e);}
        
	    PlayerCanvas canvas = new PlayerCanvas();
	    viewport = new Viewport(canvas);
	    
	    renderer = smil.getRenderer();
	    try {renderer.setCanvas(canvas);}
	    catch(Exception e){System.out.println(""+e);}
	    
	    if(d!=null)
            viewport.update(d.width, d.height);
            
        player = smil.getController();
    }
    public void closed(){
        viewport.setVisible(false);
        viewport.dispose();
        viewport = null;
    }
        
    public void setDur(double dur){
        int intpart = (int)dur;
        int decpart = (int)((dur - intpart)*1000.0); 
        String str = ""+intpart+"."+decpart;
        textFieldDur.setText(str);
    }
    public void setPos(double pos){
        int intpart = (int)pos;
        int decpart = (int)((pos - intpart)*1000.0); 
        String str = ""+intpart+"."+decpart;
        textFieldPos.setText(str);
    }
    
    
	void buttonPlay_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		if(player!=null) player.play();
	}

	void buttonPause_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		if(player!=null) player.pause();
	}

	void buttonStop_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		if(player!=null) player.stop();
	}

	void buttonClose_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		if(smil!=null) smil.close();
	}


	void buttonSetPos_ActionPerformed(java.awt.event.ActionEvent event)
	{
		String strpos = textFieldSetPos.getText();
		double pos = 0;
		try {
		    pos = Double.parseDouble(strpos.trim());
		}
		catch(NumberFormatException e){message(""+e);return;}
		if(player!=null) player.setTime(pos);
	}
}
