#ifndef __DOCHEADERS_H__
#define __DOCHEADERS_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDocHeader;

/////////////////////////////////////////////////////////////////////////////
// CDocHeaders wrapper class

class CDocHeaders : public COleDispatchDriver
{
public:
	CDocHeaders() {}		// Calls COleDispatchDriver default constructor
	CDocHeaders(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDocHeaders(const CDocHeaders& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	// method 'QueryInterface' not emitted because of invalid return type or parameter type
	unsigned long AddRef();
	unsigned long Release();
	// method 'GetTypeInfoCount' not emitted because of invalid return type or parameter type
	// method 'GetTypeInfo' not emitted because of invalid return type or parameter type
	// method 'GetIDsOfNames' not emitted because of invalid return type or parameter type
	// method 'Invoke' not emitted because of invalid return type or parameter type
	long GetCount();
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	LPUNKNOWN Get_NewEnum();
	CDocHeader Item(const VARIANT& Index);
	CDocHeader Add(LPCTSTR Name, LPCTSTR Value);
	void Remove(const VARIANT& Index);
	void Clear();
	void SetThisObject(long* ThisObject);
};

#endif // __DOCHEADERS_H__
