#ifndef __DOCHEADER_H__
#define __DOCHEADER_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDocHeader wrapper class

class CDocHeader : public COleDispatchDriver
{
public:
	CDocHeader() {}		// Calls COleDispatchDriver default constructor
	CDocHeader(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDocHeader(const CDocHeader& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	// method 'QueryInterface' not emitted because of invalid return type or parameter type
	unsigned long AddRef();
	unsigned long Release();
	// method 'GetTypeInfoCount' not emitted because of invalid return type or parameter type
	// method 'GetTypeInfo' not emitted because of invalid return type or parameter type
	// method 'GetIDsOfNames' not emitted because of invalid return type or parameter type
	// method 'Invoke' not emitted because of invalid return type or parameter type
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	CString GetValue();
	void SetValue(LPCTSTR lpszNewValue);
	void SetThisObject(long* ThisObject);
};

#endif // __DOCHEADER_H__
