#ifndef __DOCOUTPUT_H__
#define __DOCOUTPUT_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDocHeaders;

/////////////////////////////////////////////////////////////////////////////
// CDocOutput wrapper class

class CDocOutput : public COleDispatchDriver
{
public:
	CDocOutput() {}		// Calls COleDispatchDriver default constructor
	CDocOutput(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDocOutput(const CDocOutput& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	// method 'QueryInterface' not emitted because of invalid return type or parameter type
	unsigned long AddRef();
	unsigned long Release();
	// method 'GetTypeInfoCount' not emitted because of invalid return type or parameter type
	// method 'GetTypeInfo' not emitted because of invalid return type or parameter type
	// method 'GetIDsOfNames' not emitted because of invalid return type or parameter type
	// method 'Invoke' not emitted because of invalid return type or parameter type
	CDocHeaders GetHeaders();
	long GetState();
	long GetBytesTotal();
	long GetBytesTransferred();
	CString GetFileName();
	void SetFileName(LPCTSTR lpszNewValue);
	LPUNKNOWN GetDocLink();
	BOOL GetSuspended();
	BOOL GetPushStreamMode();
	void GetData(VARIANT* Data, const VARIANT& Type);
	void SetData(const VARIANT& Data);
	void Suspend(BOOL Suspend);
	long GetCPPObject();
	void SetCPPObject(long* newValue);
};

#endif // __DOCOUTPUT_H__
