#ifndef __HTMLFORM_H__
#define __HTMLFORM_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHTMLForm wrapper class

class CHTMLForm : public COleDispatchDriver
{
public:
	CHTMLForm() {}		// Calls COleDispatchDriver default constructor
	CHTMLForm(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHTMLForm(const CHTMLForm& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	// method 'QueryInterface' not emitted because of invalid return type or parameter type
	unsigned long AddRef();
	unsigned long Release();
	// method 'GetTypeInfoCount' not emitted because of invalid return type or parameter type
	// method 'GetTypeInfo' not emitted because of invalid return type or parameter type
	// method 'GetIDsOfNames' not emitted because of invalid return type or parameter type
	// method 'Invoke' not emitted because of invalid return type or parameter type
	CString GetMethod();
	CString GetUrl();
	CString GetURLEncodedBody();
	void RequestSubmit();
	long GetCPPObject();
	void SetCPPObject(long* newValue);
};

#endif // __HTMLFORM_H__
