#ifndef __HTMLFORMS_H__
#define __HTMLFORMS_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CHTMLForm;

/////////////////////////////////////////////////////////////////////////////
// CHTMLForms wrapper class

class CHTMLForms : public COleDispatchDriver
{
public:
	CHTMLForms() {}		// Calls COleDispatchDriver default constructor
	CHTMLForms(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHTMLForms(const CHTMLForms& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	// method 'QueryInterface' not emitted because of invalid return type or parameter type
	unsigned long AddRef();
	unsigned long Release();
	// method 'GetTypeInfoCount' not emitted because of invalid return type or parameter type
	// method 'GetTypeInfo' not emitted because of invalid return type or parameter type
	// method 'GetIDsOfNames' not emitted because of invalid return type or parameter type
	// method 'Invoke' not emitted because of invalid return type or parameter type
	long GetCount();
	LPUNKNOWN Get_NewEnum();
	CHTMLForm Item(const VARIANT& Index);
	long GetCPPObject();
	void SetCPPObject(long* newValue);
};

#endif // __HTMLFORMS_H__
